using System.Runtime.InteropServices;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Layouts;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.Utilities;

namespace Minis
{
    //
    // MIDI state struct with 128 notes and 128 controls
    //
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct MidiDeviceState : IInputStateTypeInfo
    {
        public FourCC format => new FourCC('D', 'I', 'D', 'I');

        #region Default Notes
        //[InputControl(name = "note000", displayName = "Note C-1" , shortDisplayName = "C-1" , layout = "MidiNote", offset = 0)]
        //[InputControl(name = "note001", displayName = "Note C#-1", shortDisplayName = "C#-1", layout = "MidiNote", offset = 1)]
        //[InputControl(name = "note002", displayName = "Note D-1" , shortDisplayName = "D-1" , layout = "MidiNote", offset = 2)]
        //[InputControl(name = "note003", displayName = "Note D#-1", shortDisplayName = "D#-1", layout = "MidiNote", offset = 3)]
        //[InputControl(name = "note004", displayName = "Note E-1" , shortDisplayName = "E-1" , layout = "MidiNote", offset = 4)]
        //[InputControl(name = "note005", displayName = "Note F-1" , shortDisplayName = "F-1" , layout = "MidiNote", offset = 5)]
        //[InputControl(name = "note006", displayName = "Note F#-1", shortDisplayName = "F#-1", layout = "MidiNote", offset = 6)]
        //[InputControl(name = "note007", displayName = "Note G-1" , shortDisplayName = "G-1" , layout = "MidiNote", offset = 7)]
        //[InputControl(name = "note008", displayName = "Note G#-1", shortDisplayName = "G#-1", layout = "MidiNote", offset = 8)]
        //[InputControl(name = "note009", displayName = "Note A-1" , shortDisplayName = "A-1" , layout = "MidiNote", offset = 9)]
        //[InputControl(name = "note010", displayName = "Note A#-1", shortDisplayName = "A#-1", layout = "MidiNote", offset = 10)]
        //[InputControl(name = "note011", displayName = "Note B-1" , shortDisplayName = "B-1" , layout = "MidiNote", offset = 11)]
        //[InputControl(name = "note012", displayName = "Note C0"  , shortDisplayName = "C0"  , layout = "MidiNote", offset = 12)]
        //[InputControl(name = "note013", displayName = "Note C#0" , shortDisplayName = "C#0" , layout = "MidiNote", offset = 13)]
        //[InputControl(name = "note014", displayName = "Note D0"  , shortDisplayName = "D0"  , layout = "MidiNote", offset = 14)]
        //[InputControl(name = "note015", displayName = "Note D#0" , shortDisplayName = "D#0" , layout = "MidiNote", offset = 15)]
        //[InputControl(name = "note016", displayName = "Note E0"  , shortDisplayName = "E0"  , layout = "MidiNote", offset = 16)]
        //[InputControl(name = "note017", displayName = "Note F0"  , shortDisplayName = "F0"  , layout = "MidiNote", offset = 17)]
        //[InputControl(name = "note018", displayName = "Note F#0" , shortDisplayName = "F#0" , layout = "MidiNote", offset = 18)]
        //[InputControl(name = "note019", displayName = "Note G0"  , shortDisplayName = "G0"  , layout = "MidiNote", offset = 19)]
        //[InputControl(name = "note020", displayName = "Note G#0" , shortDisplayName = "G#0" , layout = "MidiNote", offset = 20)]
        //[InputControl(name = "note021", displayName = "Note A0"  , shortDisplayName = "A0"  , layout = "MidiNote", offset = 21)]
        //[InputControl(name = "note022", displayName = "Note A#0" , shortDisplayName = "A#0" , layout = "MidiNote", offset = 22)]
        //[InputControl(name = "note023", displayName = "Note B0"  , shortDisplayName = "B0"  , layout = "MidiNote", offset = 23)]
        //[InputControl(name = "note024", displayName = "Note C1"  , shortDisplayName = "C1"  , layout = "MidiNote", offset = 24)]
        //[InputControl(name = "note025", displayName = "Note C#1" , shortDisplayName = "C#1" , layout = "MidiNote", offset = 25)]
        //[InputControl(name = "note026", displayName = "Note D1"  , shortDisplayName = "D1"  , layout = "MidiNote", offset = 26)]
        //[InputControl(name = "note027", displayName = "Note D#1" , shortDisplayName = "D#1" , layout = "MidiNote", offset = 27)]
        //[InputControl(name = "note028", displayName = "Note E1"  , shortDisplayName = "E1"  , layout = "MidiNote", offset = 28)]
        //[InputControl(name = "note029", displayName = "Note F1"  , shortDisplayName = "F1"  , layout = "MidiNote", offset = 29)]
        //[InputControl(name = "note030", displayName = "Note F#1" , shortDisplayName = "F#1" , layout = "MidiNote", offset = 30)]
        //[InputControl(name = "note031", displayName = "Note G1"  , shortDisplayName = "G1"  , layout = "MidiNote", offset = 31)]
        //[InputControl(name = "note032", displayName = "Note G#1" , shortDisplayName = "G#1" , layout = "MidiNote", offset = 32)]
        //[InputControl(name = "note033", displayName = "Note A1"  , shortDisplayName = "A1"  , layout = "MidiNote", offset = 33)]
        //[InputControl(name = "note034", displayName = "Note A#1" , shortDisplayName = "A#1" , layout = "MidiNote", offset = 34)]
        //[InputControl(name = "note035", displayName = "Note B1"  , shortDisplayName = "B1"  , layout = "MidiNote", offset = 35)]
        //[InputControl(name = "note036", displayName = "Note C2"  , shortDisplayName = "C2"  , layout = "MidiNote", offset = 36)]
        //[InputControl(name = "note037", displayName = "Note C#2" , shortDisplayName = "C#2" , layout = "MidiNote", offset = 37)]
        //[InputControl(name = "note038", displayName = "Note D2"  , shortDisplayName = "D2"  , layout = "MidiNote", offset = 38)]
        //[InputControl(name = "note039", displayName = "Note D#2" , shortDisplayName = "D#2" , layout = "MidiNote", offset = 39)]
        //[InputControl(name = "note040", displayName = "Note E2"  , shortDisplayName = "E2"  , layout = "MidiNote", offset = 40)]
        //[InputControl(name = "note041", displayName = "Note F2"  , shortDisplayName = "F2"  , layout = "MidiNote", offset = 41)]
        //[InputControl(name = "note042", displayName = "Note F#2" , shortDisplayName = "F#2" , layout = "MidiNote", offset = 42)]
        //[InputControl(name = "note043", displayName = "Note G2"  , shortDisplayName = "G2"  , layout = "MidiNote", offset = 43)]
        //[InputControl(name = "note044", displayName = "Note G#2" , shortDisplayName = "G#2" , layout = "MidiNote", offset = 44)]
        //[InputControl(name = "note045", displayName = "Note A2"  , shortDisplayName = "A2"  , layout = "MidiNote", offset = 45)]
        //[InputControl(name = "note046", displayName = "Note A#2" , shortDisplayName = "A#2" , layout = "MidiNote", offset = 46)]
        //[InputControl(name = "note047", displayName = "Note B2"  , shortDisplayName = "B2"  , layout = "MidiNote", offset = 47)]
        //[InputControl(name = "note048", displayName = "Note C3"  , shortDisplayName = "C3"  , layout = "MidiNote", offset = 48)]
        //[InputControl(name = "note049", displayName = "Note C#3" , shortDisplayName = "C#3" , layout = "MidiNote", offset = 49)]
        //[InputControl(name = "note050", displayName = "Note D3"  , shortDisplayName = "D3"  , layout = "MidiNote", offset = 50)]
        //[InputControl(name = "note051", displayName = "Note D#3" , shortDisplayName = "D#3" , layout = "MidiNote", offset = 51)]
        //[InputControl(name = "note052", displayName = "Note E3"  , shortDisplayName = "E3"  , layout = "MidiNote", offset = 52)]
        //[InputControl(name = "note053", displayName = "Note F3"  , shortDisplayName = "F3"  , layout = "MidiNote", offset = 53)]
        //[InputControl(name = "note054", displayName = "Note F#3" , shortDisplayName = "F#3" , layout = "MidiNote", offset = 54)]
        //[InputControl(name = "note055", displayName = "Note G3"  , shortDisplayName = "G3"  , layout = "MidiNote", offset = 55)]
        //[InputControl(name = "note056", displayName = "Note G#3" , shortDisplayName = "G#3" , layout = "MidiNote", offset = 56)]
        //[InputControl(name = "note057", displayName = "Note A3"  , shortDisplayName = "A3"  , layout = "MidiNote", offset = 57)]
        //[InputControl(name = "note058", displayName = "Note A#3" , shortDisplayName = "A#3" , layout = "MidiNote", offset = 58)]
        //[InputControl(name = "note059", displayName = "Note B3"  , shortDisplayName = "B3"  , layout = "MidiNote", offset = 59)]
        //[InputControl(name = "note060", displayName = "Note C4"  , shortDisplayName = "C4"  , layout = "MidiNote", offset = 60)]
        //[InputControl(name = "note061", displayName = "Note C#4" , shortDisplayName = "C#4" , layout = "MidiNote", offset = 61)]
        //[InputControl(name = "note062", displayName = "Note D4"  , shortDisplayName = "D4"  , layout = "MidiNote", offset = 62)]
        //[InputControl(name = "note063", displayName = "Note D#4" , shortDisplayName = "D#4" , layout = "MidiNote", offset = 63)]
        //[InputControl(name = "note064", displayName = "Note E4"  , shortDisplayName = "E4"  , layout = "MidiNote", offset = 64)]
        //[InputControl(name = "note065", displayName = "Note F4"  , shortDisplayName = "F4"  , layout = "MidiNote", offset = 65)]
        //[InputControl(name = "note066", displayName = "Note F#4" , shortDisplayName = "F#4" , layout = "MidiNote", offset = 66)]
        //[InputControl(name = "note067", displayName = "Note G4"  , shortDisplayName = "G4"  , layout = "MidiNote", offset = 67)]
        //[InputControl(name = "note068", displayName = "Note G#4" , shortDisplayName = "G#4" , layout = "MidiNote", offset = 68)]
        //[InputControl(name = "note069", displayName = "Note A4"  , shortDisplayName = "A4"  , layout = "MidiNote", offset = 69)]
        //[InputControl(name = "note070", displayName = "Note A#4" , shortDisplayName = "A#4" , layout = "MidiNote", offset = 70)]
        //[InputControl(name = "note071", displayName = "Note B4"  , shortDisplayName = "B4"  , layout = "MidiNote", offset = 71)]
        //[InputControl(name = "note072", displayName = "Note C5"  , shortDisplayName = "C5"  , layout = "MidiNote", offset = 72)]
        //[InputControl(name = "note073", displayName = "Note C#5" , shortDisplayName = "C#5" , layout = "MidiNote", offset = 73)]
        //[InputControl(name = "note074", displayName = "Note D5"  , shortDisplayName = "D5"  , layout = "MidiNote", offset = 74)]
        //[InputControl(name = "note075", displayName = "Note D#5" , shortDisplayName = "D#5" , layout = "MidiNote", offset = 75)]
        //[InputControl(name = "note076", displayName = "Note E5"  , shortDisplayName = "E5"  , layout = "MidiNote", offset = 76)]
        //[InputControl(name = "note077", displayName = "Note F5"  , shortDisplayName = "F5"  , layout = "MidiNote", offset = 77)]
        //[InputControl(name = "note078", displayName = "Note F#5" , shortDisplayName = "F#5" , layout = "MidiNote", offset = 78)]
        //[InputControl(name = "note079", displayName = "Note G5"  , shortDisplayName = "G5"  , layout = "MidiNote", offset = 79)]
        //[InputControl(name = "note080", displayName = "Note G#5" , shortDisplayName = "G#5" , layout = "MidiNote", offset = 80)]
        //[InputControl(name = "note081", displayName = "Note A5"  , shortDisplayName = "A5"  , layout = "MidiNote", offset = 81)]
        //[InputControl(name = "note082", displayName = "Note A#5" , shortDisplayName = "A#5" , layout = "MidiNote", offset = 82)]
        //[InputControl(name = "note083", displayName = "Note B5"  , shortDisplayName = "B5"  , layout = "MidiNote", offset = 83)]
        //[InputControl(name = "note084", displayName = "Note C6"  , shortDisplayName = "C6"  , layout = "MidiNote", offset = 84)]
        //[InputControl(name = "note085", displayName = "Note C#6" , shortDisplayName = "C#6" , layout = "MidiNote", offset = 85)]
        //[InputControl(name = "note086", displayName = "Note D6"  , shortDisplayName = "D6"  , layout = "MidiNote", offset = 86)]
        //[InputControl(name = "note087", displayName = "Note D#6" , shortDisplayName = "D#6" , layout = "MidiNote", offset = 87)]
        //[InputControl(name = "note088", displayName = "Note E6"  , shortDisplayName = "E6"  , layout = "MidiNote", offset = 88)]
        //[InputControl(name = "note089", displayName = "Note F6"  , shortDisplayName = "F6"  , layout = "MidiNote", offset = 89)]
        //[InputControl(name = "note090", displayName = "Note F#6" , shortDisplayName = "F#6" , layout = "MidiNote", offset = 90)]
        //[InputControl(name = "note091", displayName = "Note G6"  , shortDisplayName = "G6"  , layout = "MidiNote", offset = 91)]
        //[InputControl(name = "note092", displayName = "Note G#6" , shortDisplayName = "G#6" , layout = "MidiNote", offset = 92)]
        //[InputControl(name = "note093", displayName = "Note A6"  , shortDisplayName = "A6"  , layout = "MidiNote", offset = 93)]
        //[InputControl(name = "note094", displayName = "Note A#6" , shortDisplayName = "A#6" , layout = "MidiNote", offset = 94)]
        //[InputControl(name = "note095", displayName = "Note B6"  , shortDisplayName = "B6"  , layout = "MidiNote", offset = 95)]
        //[InputControl(name = "note096", displayName = "Note C7"  , shortDisplayName = "C7"  , layout = "MidiNote", offset = 96)]
        //[InputControl(name = "note097", displayName = "Note C#7" , shortDisplayName = "C#7" , layout = "MidiNote", offset = 97)]
        //[InputControl(name = "note098", displayName = "Note D7"  , shortDisplayName = "D7"  , layout = "MidiNote", offset = 98)]
        //[InputControl(name = "note099", displayName = "Note D#7" , shortDisplayName = "D#7" , layout = "MidiNote", offset = 99)]
        //[InputControl(name = "note100", displayName = "Note E7"  , shortDisplayName = "E7"  , layout = "MidiNote", offset = 100)]
        //[InputControl(name = "note101", displayName = "Note F7"  , shortDisplayName = "F7"  , layout = "MidiNote", offset = 101)]
        //[InputControl(name = "note102", displayName = "Note F#7" , shortDisplayName = "F#7" , layout = "MidiNote", offset = 102)]
        //[InputControl(name = "note103", displayName = "Note G7"  , shortDisplayName = "G7"  , layout = "MidiNote", offset = 103)]
        //[InputControl(name = "note104", displayName = "Note G#7" , shortDisplayName = "G#7" , layout = "MidiNote", offset = 104)]
        //[InputControl(name = "note105", displayName = "Note A7"  , shortDisplayName = "A7"  , layout = "MidiNote", offset = 105)]
        //[InputControl(name = "note106", displayName = "Note A#7" , shortDisplayName = "A#7" , layout = "MidiNote", offset = 106)]
        //[InputControl(name = "note107", displayName = "Note B7"  , shortDisplayName = "B7"  , layout = "MidiNote", offset = 107)]
        //[InputControl(name = "note108", displayName = "Note C8"  , shortDisplayName = "C8"  , layout = "MidiNote", offset = 108)]
        //[InputControl(name = "note109", displayName = "Note C#8" , shortDisplayName = "C#8" , layout = "MidiNote", offset = 109)]
        //[InputControl(name = "note110", displayName = "Note D8"  , shortDisplayName = "D8"  , layout = "MidiNote", offset = 110)]
        //[InputControl(name = "note111", displayName = "Note D#8" , shortDisplayName = "D#8" , layout = "MidiNote", offset = 111)]
        //[InputControl(name = "note112", displayName = "Note E8"  , shortDisplayName = "E8"  , layout = "MidiNote", offset = 112)]
        //[InputControl(name = "note113", displayName = "Note F8"  , shortDisplayName = "F8"  , layout = "MidiNote", offset = 113)]
        //[InputControl(name = "note114", displayName = "Note F#8" , shortDisplayName = "F#8" , layout = "MidiNote", offset = 114)]
        //[InputControl(name = "note115", displayName = "Note G8"  , shortDisplayName = "G8"  , layout = "MidiNote", offset = 115)]
        //[InputControl(name = "note116", displayName = "Note G#8" , shortDisplayName = "G#8" , layout = "MidiNote", offset = 116)]
        //[InputControl(name = "note117", displayName = "Note A8"  , shortDisplayName = "A8"  , layout = "MidiNote", offset = 117)]
        //[InputControl(name = "note118", displayName = "Note A#8" , shortDisplayName = "A#8" , layout = "MidiNote", offset = 118)]
        //[InputControl(name = "note119", displayName = "Note B8"  , shortDisplayName = "B8"  , layout = "MidiNote", offset = 119)]
        //[InputControl(name = "note120", displayName = "Note C9"  , shortDisplayName = "C9"  , layout = "MidiNote", offset = 120)]
        //[InputControl(name = "note121", displayName = "Note C#9" , shortDisplayName = "C#9" , layout = "MidiNote", offset = 121)]
        //[InputControl(name = "note122", displayName = "Note D9"  , shortDisplayName = "D9"  , layout = "MidiNote", offset = 122)]
        //[InputControl(name = "note123", displayName = "Note D#9" , shortDisplayName = "D#9" , layout = "MidiNote", offset = 123)]
        //[InputControl(name = "note124", displayName = "Note E9"  , shortDisplayName = "E9"  , layout = "MidiNote", offset = 124)]
        //[InputControl(name = "note125", displayName = "Note F9"  , shortDisplayName = "F9"  , layout = "MidiNote", offset = 125)]
        //[InputControl(name = "note126", displayName = "Note F#9" , shortDisplayName = "F#9" , layout = "MidiNote", offset = 126)]
        //[InputControl(name = "note127", displayName = "Note G9"  , shortDisplayName = "G9"  , layout = "MidiNote", offset = 127)]
        //public fixed byte notes[128];
        #endregion

        #region Default ControlChanges
        [InputControl(name = "DonoControl000", displayName = "DonoControl 0"  , shortDisplayName = "DCC 0"  , layout = "MidiValue", offset = 128)]
        [InputControl(name = "DonoControl001", displayName = "DonoControl 1"  , shortDisplayName = "DCC 1"  , layout = "MidiValue", offset = 129)]
        [InputControl(name = "DonoControl002", displayName = "DonoControl 2"  , shortDisplayName = "DCC 2"  , layout = "MidiValue", offset = 130)]
        [InputControl(name = "DonoControl003", displayName = "DonoControl 3"  , shortDisplayName = "DCC 3"  , layout = "MidiValue", offset = 131)]
        [InputControl(name = "DonoControl004", displayName = "DonoControl 4"  , shortDisplayName = "DCC 4"  , layout = "MidiValue", offset = 132)]
        [InputControl(name = "DonoControl005", displayName = "DonoControl 5"  , shortDisplayName = "DCC 5"  , layout = "MidiValue", offset = 133)]
        [InputControl(name = "DonoControl006", displayName = "DonoControl 6"  , shortDisplayName = "DCC 6"  , layout = "MidiValue", offset = 134)]
        [InputControl(name = "DonoControl007", displayName = "DonoControl 7"  , shortDisplayName = "DCC 7"  , layout = "MidiValue", offset = 135)]
        [InputControl(name = "DonoControl008", displayName = "DonoControl 8"  , shortDisplayName = "DCC 8"  , layout = "MidiValue", offset = 136)]
        [InputControl(name = "DonoControl009", displayName = "DonoControl 9"  , shortDisplayName = "DCC 9"  , layout = "MidiValue", offset = 137)]
        [InputControl(name = "DonoControl010", displayName = "DonoControl 10" , shortDisplayName = "DCC 10" , layout = "MidiValue", offset = 138)]
        [InputControl(name = "DonoControl011", displayName = "DonoControl 11" , shortDisplayName = "DCC 11" , layout = "MidiValue", offset = 139)]
        [InputControl(name = "DonoControl012", displayName = "DonoControl 12" , shortDisplayName = "DCC 12" , layout = "MidiValue", offset = 140)]
        [InputControl(name = "DonoControl013", displayName = "DonoControl 13" , shortDisplayName = "DCC 13" , layout = "MidiValue", offset = 141)]
        [InputControl(name = "DonoControl014", displayName = "DonoControl 14" , shortDisplayName = "DCC 14" , layout = "MidiValue", offset = 142)]
        [InputControl(name = "DonoControl015", displayName = "DonoControl 15" , shortDisplayName = "DCC 15" , layout = "MidiValue", offset = 143)]
        [InputControl(name = "DonoControl016", displayName = "DonoControl 16" , shortDisplayName = "DCC 16" , layout = "MidiValue", offset = 144)]
        [InputControl(name = "DonoControl017", displayName = "DonoControl 17" , shortDisplayName = "DCC 17" , layout = "MidiValue", offset = 145)]
        [InputControl(name = "DonoControl018", displayName = "DonoControl 18" , shortDisplayName = "DCC 18" , layout = "MidiValue", offset = 146)]
        [InputControl(name = "DonoControl019", displayName = "DonoControl 19" , shortDisplayName = "DCC 19" , layout = "MidiValue", offset = 147)]
        [InputControl(name = "DonoControl020", displayName = "DonoControl 20" , shortDisplayName = "DCC 20" , layout = "MidiValue", offset = 148)]
        [InputControl(name = "DonoControl021", displayName = "DonoControl 21" , shortDisplayName = "DCC 21" , layout = "MidiValue", offset = 149)]
        [InputControl(name = "DonoControl022", displayName = "DonoControl 22" , shortDisplayName = "DCC 22" , layout = "MidiValue", offset = 150)]
        [InputControl(name = "DonoControl023", displayName = "DonoControl 23" , shortDisplayName = "DCC 23" , layout = "MidiValue", offset = 151)]
        [InputControl(name = "DonoControl024", displayName = "DonoControl 24" , shortDisplayName = "DCC 24" , layout = "MidiValue", offset = 152)]
        [InputControl(name = "DonoControl025", displayName = "DonoControl 25" , shortDisplayName = "DCC 25" , layout = "MidiValue", offset = 153)]
        [InputControl(name = "DonoControl026", displayName = "DonoControl 26" , shortDisplayName = "DCC 26" , layout = "MidiValue", offset = 154)]
        [InputControl(name = "DonoControl027", displayName = "DonoControl 27" , shortDisplayName = "DCC 27" , layout = "MidiValue", offset = 155)]
        [InputControl(name = "DonoControl028", displayName = "DonoControl 28" , shortDisplayName = "DCC 28" , layout = "MidiValue", offset = 156)]
        [InputControl(name = "DonoControl029", displayName = "DonoControl 29" , shortDisplayName = "DCC 29" , layout = "MidiValue", offset = 157)]
        [InputControl(name = "DonoControl030", displayName = "DonoControl 30" , shortDisplayName = "DCC 30" , layout = "MidiValue", offset = 158)]
        [InputControl(name = "DonoControl031", displayName = "DonoControl 31" , shortDisplayName = "DCC 31" , layout = "MidiValue", offset = 159)]
        [InputControl(name = "DonoControl032", displayName = "DonoControl 32" , shortDisplayName = "DCC 32" , layout = "MidiValue", offset = 160)]
        [InputControl(name = "DonoControl033", displayName = "DonoControl 33" , shortDisplayName = "DCC 33" , layout = "MidiValue", offset = 161)]
        [InputControl(name = "DonoControl034", displayName = "DonoControl 34" , shortDisplayName = "DCC 34" , layout = "MidiValue", offset = 162)]
        [InputControl(name = "DonoControl035", displayName = "DonoControl 35" , shortDisplayName = "DCC 35" , layout = "MidiValue", offset = 163)]
        [InputControl(name = "DonoControl036", displayName = "DonoControl 36" , shortDisplayName = "DCC 36" , layout = "MidiValue", offset = 164)]
        [InputControl(name = "DonoControl037", displayName = "DonoControl 37" , shortDisplayName = "DCC 37" , layout = "MidiValue", offset = 165)]
        [InputControl(name = "DonoControl038", displayName = "DonoControl 38" , shortDisplayName = "DCC 38" , layout = "MidiValue", offset = 166)]
        [InputControl(name = "DonoControl039", displayName = "DonoControl 39" , shortDisplayName = "DCC 39" , layout = "MidiValue", offset = 167)]
        [InputControl(name = "DonoControl040", displayName = "DonoControl 40" , shortDisplayName = "DCC 40" , layout = "MidiValue", offset = 168)]
        [InputControl(name = "DonoControl041", displayName = "DonoControl 41" , shortDisplayName = "DCC 41" , layout = "MidiValue", offset = 169)]
        [InputControl(name = "DonoControl042", displayName = "DonoControl 42" , shortDisplayName = "DCC 42" , layout = "MidiValue", offset = 170)]
        [InputControl(name = "DonoControl043", displayName = "DonoControl 43" , shortDisplayName = "DCC 43" , layout = "MidiValue", offset = 171)]
        [InputControl(name = "DonoControl044", displayName = "DonoControl 44" , shortDisplayName = "DCC 44" , layout = "MidiValue", offset = 172)]
        [InputControl(name = "DonoControl045", displayName = "DonoControl 45" , shortDisplayName = "DCC 45" , layout = "MidiValue", offset = 173)]
        [InputControl(name = "DonoControl046", displayName = "DonoControl 46" , shortDisplayName = "DCC 46" , layout = "MidiValue", offset = 174)]
        [InputControl(name = "DonoControl047", displayName = "DonoControl 47" , shortDisplayName = "DCC 47" , layout = "MidiValue", offset = 175)]
        [InputControl(name = "DonoControl048", displayName = "DonoControl 48" , shortDisplayName = "DCC 48" , layout = "MidiValue", offset = 176)]
        [InputControl(name = "DonoControl049", displayName = "DonoControl 49" , shortDisplayName = "DCC 49" , layout = "MidiValue", offset = 177)]
        [InputControl(name = "DonoControl050", displayName = "DonoControl 50" , shortDisplayName = "DCC 50" , layout = "MidiValue", offset = 178)]
        [InputControl(name = "DonoControl051", displayName = "DonoControl 51" , shortDisplayName = "DCC 51" , layout = "MidiValue", offset = 179)]
        [InputControl(name = "DonoControl052", displayName = "DonoControl 52" , shortDisplayName = "DCC 52" , layout = "MidiValue", offset = 180)]
        [InputControl(name = "DonoControl053", displayName = "DonoControl 53" , shortDisplayName = "DCC 53" , layout = "MidiValue", offset = 181)]
        [InputControl(name = "DonoControl054", displayName = "DonoControl 54" , shortDisplayName = "DCC 54" , layout = "MidiValue", offset = 182)]
        [InputControl(name = "DonoControl055", displayName = "DonoControl 55" , shortDisplayName = "DCC 55" , layout = "MidiValue", offset = 183)]
        [InputControl(name = "DonoControl056", displayName = "DonoControl 56" , shortDisplayName = "DCC 56" , layout = "MidiValue", offset = 184)]
        [InputControl(name = "DonoControl057", displayName = "DonoControl 57" , shortDisplayName = "DCC 57" , layout = "MidiValue", offset = 185)]
        [InputControl(name = "DonoControl058", displayName = "DonoControl 58" , shortDisplayName = "DCC 58" , layout = "MidiValue", offset = 186)]
        [InputControl(name = "DonoControl059", displayName = "DonoControl 59" , shortDisplayName = "DCC 59" , layout = "MidiValue", offset = 187)]
        [InputControl(name = "DonoControl060", displayName = "DonoControl 60" , shortDisplayName = "DCC 60" , layout = "MidiValue", offset = 188)]
        [InputControl(name = "DonoControl061", displayName = "DonoControl 61" , shortDisplayName = "DCC 61" , layout = "MidiValue", offset = 189)]
        [InputControl(name = "DonoControl062", displayName = "DonoControl 62" , shortDisplayName = "DCC 62" , layout = "MidiValue", offset = 190)]
        [InputControl(name = "DonoControl063", displayName = "DonoControl 63" , shortDisplayName = "DCC 63" , layout = "MidiValue", offset = 191)]
        [InputControl(name = "DonoControl064", displayName = "DonoControl 64" , shortDisplayName = "DCC 64" , layout = "MidiValue", offset = 192)]
        [InputControl(name = "DonoControl065", displayName = "DonoControl 65" , shortDisplayName = "DCC 65" , layout = "MidiValue", offset = 193)]
        [InputControl(name = "DonoControl066", displayName = "DonoControl 66" , shortDisplayName = "DCC 66" , layout = "MidiValue", offset = 194)]
        [InputControl(name = "DonoControl067", displayName = "DonoControl 67" , shortDisplayName = "DCC 67" , layout = "MidiValue", offset = 195)]
        [InputControl(name = "DonoControl068", displayName = "DonoControl 68" , shortDisplayName = "DCC 68" , layout = "MidiValue", offset = 196)]
        [InputControl(name = "DonoControl069", displayName = "DonoControl 69" , shortDisplayName = "DCC 69" , layout = "MidiValue", offset = 197)]
        [InputControl(name = "DonoControl070", displayName = "DonoControl 70" , shortDisplayName = "DCC 70" , layout = "MidiValue", offset = 198)]
        [InputControl(name = "DonoControl071", displayName = "DonoControl 71" , shortDisplayName = "DCC 71" , layout = "MidiValue", offset = 199)]
        [InputControl(name = "DonoControl072", displayName = "DonoControl 72" , shortDisplayName = "DCC 72" , layout = "MidiValue", offset = 200)]
        [InputControl(name = "DonoControl073", displayName = "DonoControl 73" , shortDisplayName = "DCC 73" , layout = "MidiValue", offset = 201)]
        [InputControl(name = "DonoControl074", displayName = "DonoControl 74" , shortDisplayName = "DCC 74" , layout = "MidiValue", offset = 202)]
        [InputControl(name = "DonoControl075", displayName = "DonoControl 75" , shortDisplayName = "DCC 75" , layout = "MidiValue", offset = 203)]
        [InputControl(name = "DonoControl076", displayName = "DonoControl 76" , shortDisplayName = "DCC 76" , layout = "MidiValue", offset = 204)]
        [InputControl(name = "DonoControl077", displayName = "DonoControl 77" , shortDisplayName = "DCC 77" , layout = "MidiValue", offset = 205)]
        [InputControl(name = "DonoControl078", displayName = "DonoControl 78" , shortDisplayName = "DCC 78" , layout = "MidiValue", offset = 206)]
        [InputControl(name = "DonoControl079", displayName = "DonoControl 79" , shortDisplayName = "DCC 79" , layout = "MidiValue", offset = 207)]
        [InputControl(name = "DonoControl080", displayName = "DonoControl 80" , shortDisplayName = "DCC 80" , layout = "MidiValue", offset = 208)]
        [InputControl(name = "DonoControl081", displayName = "DonoControl 81" , shortDisplayName = "DCC 81" , layout = "MidiValue", offset = 209)]
        [InputControl(name = "DonoControl082", displayName = "DonoControl 82" , shortDisplayName = "DCC 82" , layout = "MidiValue", offset = 210)]
        [InputControl(name = "DonoControl083", displayName = "DonoControl 83" , shortDisplayName = "DCC 83" , layout = "MidiValue", offset = 211)]
        [InputControl(name = "DonoControl084", displayName = "DonoControl 84" , shortDisplayName = "DCC 84" , layout = "MidiValue", offset = 212)]
        [InputControl(name = "DonoControl085", displayName = "DonoControl 85" , shortDisplayName = "DCC 85" , layout = "MidiValue", offset = 213)]
        [InputControl(name = "DonoControl086", displayName = "DonoControl 86" , shortDisplayName = "DCC 86" , layout = "MidiValue", offset = 214)]
        [InputControl(name = "DonoControl087", displayName = "DonoControl 87" , shortDisplayName = "DCC 87" , layout = "MidiValue", offset = 215)]
        [InputControl(name = "DonoControl088", displayName = "DonoControl 88" , shortDisplayName = "DCC 88" , layout = "MidiValue", offset = 216)]
        [InputControl(name = "DonoControl089", displayName = "DonoControl 89" , shortDisplayName = "DCC 89" , layout = "MidiValue", offset = 217)]
        [InputControl(name = "DonoControl090", displayName = "DonoControl 90" , shortDisplayName = "DCC 90" , layout = "MidiValue", offset = 218)]
        [InputControl(name = "DonoControl091", displayName = "DonoControl 91" , shortDisplayName = "DCC 91" , layout = "MidiValue", offset = 219)]
        [InputControl(name = "DonoControl092", displayName = "DonoControl 92" , shortDisplayName = "DCC 92" , layout = "MidiValue", offset = 220)]
        [InputControl(name = "DonoControl093", displayName = "DonoControl 93" , shortDisplayName = "DCC 93" , layout = "MidiValue", offset = 221)]
        [InputControl(name = "DonoControl094", displayName = "DonoControl 94" , shortDisplayName = "DCC 94" , layout = "MidiValue", offset = 222)]
        [InputControl(name = "DonoControl095", displayName = "DonoControl 95" , shortDisplayName = "DCC 95" , layout = "MidiValue", offset = 223)]
        [InputControl(name = "DonoControl096", displayName = "DonoControl 96" , shortDisplayName = "DCC 96" , layout = "MidiValue", offset = 224)]
        [InputControl(name = "DonoControl097", displayName = "DonoControl 97" , shortDisplayName = "DCC 97" , layout = "MidiValue", offset = 225)]
        [InputControl(name = "DonoControl098", displayName = "DonoControl 98" , shortDisplayName = "DCC 98" , layout = "MidiValue", offset = 226)]
        [InputControl(name = "DonoControl099", displayName = "DonoControl 99" , shortDisplayName = "DCC 99" , layout = "MidiValue", offset = 227)]
        [InputControl(name = "DonoControl100", displayName = "DonoControl 100", shortDisplayName = "DCC 100", layout = "MidiValue", offset = 228)]
        [InputControl(name = "DonoControl101", displayName = "DonoControl 101", shortDisplayName = "DCC 101", layout = "MidiValue", offset = 229)]
        [InputControl(name = "DonoControl102", displayName = "DonoControl 102", shortDisplayName = "DCC 102", layout = "MidiValue", offset = 230)]
        [InputControl(name = "DonoControl103", displayName = "DonoControl 103", shortDisplayName = "DCC 103", layout = "MidiValue", offset = 231)]
        [InputControl(name = "DonoControl104", displayName = "DonoControl 104", shortDisplayName = "DCC 104", layout = "MidiValue", offset = 232)]
        [InputControl(name = "DonoControl105", displayName = "DonoControl 105", shortDisplayName = "DCC 105", layout = "MidiValue", offset = 233)]
        [InputControl(name = "DonoControl106", displayName = "DonoControl 106", shortDisplayName = "DCC 106", layout = "MidiValue", offset = 234)]
        [InputControl(name = "DonoControl107", displayName = "DonoControl 107", shortDisplayName = "DCC 107", layout = "MidiValue", offset = 235)]
        [InputControl(name = "DonoControl108", displayName = "DonoControl 108", shortDisplayName = "DCC 108", layout = "MidiValue", offset = 236)]
        [InputControl(name = "DonoControl109", displayName = "DonoControl 109", shortDisplayName = "DCC 109", layout = "MidiValue", offset = 237)]
        [InputControl(name = "DonoControl110", displayName = "DonoControl 110", shortDisplayName = "DCC 110", layout = "MidiValue", offset = 238)]
        [InputControl(name = "DonoControl111", displayName = "DonoControl 111", shortDisplayName = "DCC 111", layout = "MidiValue", offset = 239)]
        [InputControl(name = "DonoControl112", displayName = "DonoControl 112", shortDisplayName = "DCC 112", layout = "MidiValue", offset = 240)]
        [InputControl(name = "DonoControl113", displayName = "DonoControl 113", shortDisplayName = "DCC 113", layout = "MidiValue", offset = 241)]
        [InputControl(name = "DonoControl114", displayName = "DonoControl 114", shortDisplayName = "DCC 114", layout = "MidiValue", offset = 242)]
        [InputControl(name = "DonoControl115", displayName = "DonoControl 115", shortDisplayName = "DCC 115", layout = "MidiValue", offset = 243)]
        [InputControl(name = "DonoControl116", displayName = "DonoControl 116", shortDisplayName = "DCC 116", layout = "MidiValue", offset = 244)]
        [InputControl(name = "DonoControl117", displayName = "DonoControl 117", shortDisplayName = "DCC 117", layout = "MidiValue", offset = 245)]
        [InputControl(name = "DonoControl118", displayName = "DonoControl 118", shortDisplayName = "DCC 118", layout = "MidiValue", offset = 246)]
        [InputControl(name = "DonoControl119", displayName = "DonoControl 119", shortDisplayName = "DCC 119", layout = "MidiValue", offset = 247)]
        [InputControl(name = "DonoControl120", displayName = "DonoControl 120", shortDisplayName = "DCC 120", layout = "MidiValue", offset = 248)]
        [InputControl(name = "DonoControl121", displayName = "DonoControl 121", shortDisplayName = "DCC 121", layout = "MidiValue", offset = 249)]
        [InputControl(name = "DonoControl122", displayName = "DonoControl 122", shortDisplayName = "DCC 122", layout = "MidiValue", offset = 250)]
        [InputControl(name = "DonoControl123", displayName = "DonoControl 123", shortDisplayName = "DCC 123", layout = "MidiValue", offset = 251)]
        [InputControl(name = "DonoControl124", displayName = "DonoControl 124", shortDisplayName = "DCC 124", layout = "MidiValue", offset = 252)]
        [InputControl(name = "DonoControl125", displayName = "DonoControl 125", shortDisplayName = "DCC 125", layout = "MidiValue", offset = 253)]
        [InputControl(name = "DonoControl126", displayName = "DonoControl 126", shortDisplayName = "DCC 126", layout = "MidiValue", offset = 254)]
        [InputControl(name = "DonoControl127", displayName = "DonoControl 127", shortDisplayName = "DCC 127", layout = "MidiValue", offset = 255)]
        public fixed byte controls[128];
        #endregion

        #region Dono Notes
        [InputControl(name = "DonoNote000", displayName = "DonoNote C-1", shortDisplayName = "DN C-1", layout = "MidiNote", offset = 0)]
        [InputControl(name = "DonoNote001", displayName = "DonoNote C#-1", shortDisplayName = "DN C#-1", layout = "MidiNote", offset = 1)]
        [InputControl(name = "DonoNote002", displayName = "DonoNote D-1", shortDisplayName = "DN D-1", layout = "MidiNote", offset = 2)]
        [InputControl(name = "DonoNote003", displayName = "DonoNote D#-1", shortDisplayName = "DN D#-1", layout = "MidiNote", offset = 3)]
        [InputControl(name = "DonoNote004", displayName = "DonoNote E-1", shortDisplayName = "DN E-1", layout = "MidiNote", offset = 4)]
        [InputControl(name = "DonoNote005", displayName = "DonoNote F-1", shortDisplayName = "DN F-1", layout = "MidiNote", offset = 5)]
        [InputControl(name = "DonoNote006", displayName = "DonoNote F#-1", shortDisplayName = "DN F#-1", layout = "MidiNote", offset = 6)]
        [InputControl(name = "DonoNote007", displayName = "DonoNote G-1", shortDisplayName = "DN G-1", layout = "MidiNote", offset = 7)]
        [InputControl(name = "DonoNote008", displayName = "DonoNote G#-1", shortDisplayName = "DN G#-1", layout = "MidiNote", offset = 8)]
        [InputControl(name = "DonoNote009", displayName = "DonoNote A-1", shortDisplayName = "DN A-1", layout = "MidiNote", offset = 9)]
        [InputControl(name = "DonoNote010", displayName = "DonoNote A#-1", shortDisplayName = "DN A#-1", layout = "MidiNote", offset = 10)]
        [InputControl(name = "DonoNote011", displayName = "DonoNote B-1", shortDisplayName = "DN B-1", layout = "MidiNote", offset = 11)]
        [InputControl(name = "DonoNote012", displayName = "DonoNote C0", shortDisplayName = "DN C0", layout = "MidiNote", offset = 12)]
        [InputControl(name = "DonoNote013", displayName = "DonoNote C#0", shortDisplayName = "DN C#0", layout = "MidiNote", offset = 13)]
        [InputControl(name = "DonoNote014", displayName = "DonoNote D0", shortDisplayName = "DN D0", layout = "MidiNote", offset = 14)]
        [InputControl(name = "DonoNote015", displayName = "DonoNote D#0", shortDisplayName = "DN D#0", layout = "MidiNote", offset = 15)]
        [InputControl(name = "DonoNote016", displayName = "DonoNote E0", shortDisplayName = "DN E0", layout = "MidiNote", offset = 16)]
        [InputControl(name = "DonoNote017", displayName = "DonoNote F0", shortDisplayName = "DN F0", layout = "MidiNote", offset = 17)]
        [InputControl(name = "DonoNote018", displayName = "DonoNote F#0", shortDisplayName = "DN F#0", layout = "MidiNote", offset = 18)]
        [InputControl(name = "DonoNote019", displayName = "DonoNote G0", shortDisplayName = "DN G0", layout = "MidiNote", offset = 19)]
        [InputControl(name = "DonoNote020", displayName = "DonoNote G#0", shortDisplayName = "DN G#0", layout = "MidiNote", offset = 20)]
        [InputControl(name = "DonoNote021", displayName = "DonoNote A0", shortDisplayName = "DN A0", layout = "MidiNote", offset = 21)]
        [InputControl(name = "DonoNote022", displayName = "DonoNote A#0", shortDisplayName = "DN A#0", layout = "MidiNote", offset = 22)]
        [InputControl(name = "DonoNote023", displayName = "DonoNote B0", shortDisplayName = "DN B0", layout = "MidiNote", offset = 23)]
        [InputControl(name = "DonoNote024", displayName = "DonoNote C1", shortDisplayName = "DN C1", layout = "MidiNote", offset = 24)]
        [InputControl(name = "DonoNote025", displayName = "DonoNote C#1", shortDisplayName = "DN C#1", layout = "MidiNote", offset = 25)]
        [InputControl(name = "DonoNote026", displayName = "DonoNote D1", shortDisplayName = "DN D1", layout = "MidiNote", offset = 26)]
        [InputControl(name = "DonoNote027", displayName = "DonoNote D#1", shortDisplayName = "DN D#1", layout = "MidiNote", offset = 27)]
        [InputControl(name = "DonoNote028", displayName = "DonoNote E1", shortDisplayName = "DN E1", layout = "MidiNote", offset = 28)]
        [InputControl(name = "DonoNote029", displayName = "DonoNote F1", shortDisplayName = "DN F1", layout = "MidiNote", offset = 29)]
        [InputControl(name = "DonoNote030", displayName = "DonoNote F#1", shortDisplayName = "DN F#1", layout = "MidiNote", offset = 30)]
        [InputControl(name = "DonoNote031", displayName = "DonoNote G1", shortDisplayName = "DN G1", layout = "MidiNote", offset = 31)]
        [InputControl(name = "DonoNote032", displayName = "DonoNote G#1", shortDisplayName = "DN G#1", layout = "MidiNote", offset = 32)]
        [InputControl(name = "DonoNote033", displayName = "DonoNote A1", shortDisplayName = "DN A1", layout = "MidiNote", offset = 33)]
        [InputControl(name = "DonoNote034", displayName = "DonoNote A#1", shortDisplayName = "DN A#1", layout = "MidiNote", offset = 34)]
        [InputControl(name = "DonoNote035", displayName = "DonoNote B1", shortDisplayName = "DN B1", layout = "MidiNote", offset = 35)]
        [InputControl(name = "DonoNote036", displayName = "DonoNote C2", shortDisplayName = "DN C2", layout = "MidiNote", offset = 36)]
        [InputControl(name = "DonoNote037", displayName = "DonoNote C#2", shortDisplayName = "DN C#2", layout = "MidiNote", offset = 37)]
        [InputControl(name = "DonoNote038", displayName = "DonoNote D2", shortDisplayName = "DN D2", layout = "MidiNote", offset = 38)]
        [InputControl(name = "DonoNote039", displayName = "DonoNote D#2", shortDisplayName = "DN D#2", layout = "MidiNote", offset = 39)]
        [InputControl(name = "DonoNote040", displayName = "DonoNote E2", shortDisplayName = "DN E2", layout = "MidiNote", offset = 40)]
        [InputControl(name = "DonoNote041", displayName = "DonoNote F2", shortDisplayName = "DN F2", layout = "MidiNote", offset = 41)]
        [InputControl(name = "DonoNote042", displayName = "DonoNote F#2", shortDisplayName = "DN F#2", layout = "MidiNote", offset = 42)]
        [InputControl(name = "DonoNote043", displayName = "DonoNote G2", shortDisplayName = "DN G2", layout = "MidiNote", offset = 43)]
        [InputControl(name = "DonoNote044", displayName = "DonoNote G#2", shortDisplayName = "DN G#2", layout = "MidiNote", offset = 44)]
        [InputControl(name = "DonoNote045", displayName = "DonoNote A2", shortDisplayName = "DN A2", layout = "MidiNote", offset = 45)]
        [InputControl(name = "DonoNote046", displayName = "DonoNote A#2", shortDisplayName = "DN A#2", layout = "MidiNote", offset = 46)]
        [InputControl(name = "DonoNote047", displayName = "DonoNote B2", shortDisplayName = "DN B2", layout = "MidiNote", offset = 47)]
        [InputControl(name = "DonoNote048", displayName = "DonoNote C3", shortDisplayName = "DN C3", layout = "MidiNote", offset = 48)]
        [InputControl(name = "DonoNote049", displayName = "DonoNote C#3", shortDisplayName = "DN C#3", layout = "MidiNote", offset = 49)]
        [InputControl(name = "DonoNote050", displayName = "DonoNote D3", shortDisplayName = "DN D3", layout = "MidiNote", offset = 50)]
        [InputControl(name = "DonoNote051", displayName = "DonoNote D#3", shortDisplayName = "DN D#3", layout = "MidiNote", offset = 51)]
        [InputControl(name = "DonoNote052", displayName = "DonoNote E3", shortDisplayName = "DN E3", layout = "MidiNote", offset = 52)]
        [InputControl(name = "DonoNote053", displayName = "DonoNote F3", shortDisplayName = "DN F3", layout = "MidiNote", offset = 53)]
        [InputControl(name = "DonoNote054", displayName = "DonoNote F#3", shortDisplayName = "DN F#3", layout = "MidiNote", offset = 54)]
        [InputControl(name = "DonoNote055", displayName = "DonoNote G3", shortDisplayName = "DN G3", layout = "MidiNote", offset = 55)]
        [InputControl(name = "DonoNote056", displayName = "DonoNote G#3", shortDisplayName = "DN G#3", layout = "MidiNote", offset = 56)]
        [InputControl(name = "DonoNote057", displayName = "DonoNote A3", shortDisplayName = "DN A3", layout = "MidiNote", offset = 57)]
        [InputControl(name = "DonoNote058", displayName = "DonoNote A#3", shortDisplayName = "DN A#3", layout = "MidiNote", offset = 58)]
        [InputControl(name = "DonoNote059", displayName = "DonoNote B3", shortDisplayName = "DN B3", layout = "MidiNote", offset = 59)]
        [InputControl(name = "DonoNote060", displayName = "DonoNote C4", shortDisplayName = "DN C4", layout = "MidiNote", offset = 60)]
        [InputControl(name = "DonoNote061", displayName = "DonoNote C#4", shortDisplayName = "DN C#4", layout = "MidiNote", offset = 61)]
        [InputControl(name = "DonoNote062", displayName = "DonoNote D4", shortDisplayName = "DN D4", layout = "MidiNote", offset = 62)]
        [InputControl(name = "DonoNote063", displayName = "DonoNote D#4", shortDisplayName = "DN D#4", layout = "MidiNote", offset = 63)]
        [InputControl(name = "DonoNote064", displayName = "DonoNote E4", shortDisplayName = "DN E4", layout = "MidiNote", offset = 64)]
        [InputControl(name = "DonoNote065", displayName = "DonoNote F4", shortDisplayName = "DN F4", layout = "MidiNote", offset = 65)]
        [InputControl(name = "DonoNote066", displayName = "DonoNote F#4", shortDisplayName = "DN F#4", layout = "MidiNote", offset = 66)]
        [InputControl(name = "DonoNote067", displayName = "DonoNote G4", shortDisplayName = "DN G4", layout = "MidiNote", offset = 67)]
        [InputControl(name = "DonoNote068", displayName = "DonoNote G#4", shortDisplayName = "DN G#4", layout = "MidiNote", offset = 68)]
        [InputControl(name = "DonoNote069", displayName = "DonoNote A4", shortDisplayName = "DN A4", layout = "MidiNote", offset = 69)]
        [InputControl(name = "DonoNote070", displayName = "DonoNote A#4", shortDisplayName = "DN A#4", layout = "MidiNote", offset = 70)]
        [InputControl(name = "DonoNote071", displayName = "DonoNote B4", shortDisplayName = "DN B4", layout = "MidiNote", offset = 71)]
        [InputControl(name = "DonoNote072", displayName = "DonoNote C5", shortDisplayName = "DN C5", layout = "MidiNote", offset = 72)]
        [InputControl(name = "DonoNote073", displayName = "DonoNote C#5", shortDisplayName = "DN C#5", layout = "MidiNote", offset = 73)]
        [InputControl(name = "DonoNote074", displayName = "DonoNote D5", shortDisplayName = "DN D5", layout = "MidiNote", offset = 74)]
        [InputControl(name = "DonoNote075", displayName = "DonoNote D#5", shortDisplayName = "DN D#5", layout = "MidiNote", offset = 75)]
        [InputControl(name = "DonoNote076", displayName = "DonoNote E5", shortDisplayName = "DN E5", layout = "MidiNote", offset = 76)]
        [InputControl(name = "DonoNote077", displayName = "DonoNote F5", shortDisplayName = "DN F5", layout = "MidiNote", offset = 77)]
        [InputControl(name = "DonoNote078", displayName = "DonoNote F#5", shortDisplayName = "DN F#5", layout = "MidiNote", offset = 78)]
        [InputControl(name = "DonoNote079", displayName = "DonoNote G5", shortDisplayName = "DN G5", layout = "MidiNote", offset = 79)]
        [InputControl(name = "DonoNote080", displayName = "DonoNote G#5", shortDisplayName = "DN G#5", layout = "MidiNote", offset = 80)]
        [InputControl(name = "DonoNote081", displayName = "DonoNote A5", shortDisplayName = "DN A5", layout = "MidiNote", offset = 81)]
        [InputControl(name = "DonoNote082", displayName = "DonoNote A#5", shortDisplayName = "DN A#5", layout = "MidiNote", offset = 82)]
        [InputControl(name = "DonoNote083", displayName = "DonoNote B5", shortDisplayName = "DN B5", layout = "MidiNote", offset = 83)]
        [InputControl(name = "DonoNote084", displayName = "DonoNote C6", shortDisplayName = "DN C6", layout = "MidiNote", offset = 84)]
        [InputControl(name = "DonoNote085", displayName = "DonoNote C#6", shortDisplayName = "DN C#6", layout = "MidiNote", offset = 85)]
        [InputControl(name = "DonoNote086", displayName = "DonoNote D6", shortDisplayName = "DN D6", layout = "MidiNote", offset = 86)]
        [InputControl(name = "DonoNote087", displayName = "DonoNote D#6", shortDisplayName = "DN D#6", layout = "MidiNote", offset = 87)]
        [InputControl(name = "DonoNote088", displayName = "DonoNote E6", shortDisplayName = "DN E6", layout = "MidiNote", offset = 88)]
        [InputControl(name = "DonoNote089", displayName = "DonoNote F6", shortDisplayName = "DN F6", layout = "MidiNote", offset = 89)]
        [InputControl(name = "DonoNote090", displayName = "DonoNote F#6", shortDisplayName = "DN F#6", layout = "MidiNote", offset = 90)]
        [InputControl(name = "DonoNote091", displayName = "DonoNote G6", shortDisplayName = "DN G6", layout = "MidiNote", offset = 91)]
        [InputControl(name = "DonoNote092", displayName = "DonoNote G#6", shortDisplayName = "DN G#6", layout = "MidiNote", offset = 92)]
        [InputControl(name = "DonoNote093", displayName = "DonoNote A6", shortDisplayName = "DN A6", layout = "MidiNote", offset = 93)]
        [InputControl(name = "DonoNote094", displayName = "DonoNote A#6", shortDisplayName = "DN A#6", layout = "MidiNote", offset = 94)]
        [InputControl(name = "DonoNote095", displayName = "DonoNote B6", shortDisplayName = "DN B6", layout = "MidiNote", offset = 95)]
        [InputControl(name = "DonoNote096", displayName = "DonoNote C7", shortDisplayName = "DN C7", layout = "MidiNote", offset = 96)]
        [InputControl(name = "DonoNote097", displayName = "DonoNote C#7", shortDisplayName = "DN C#7", layout = "MidiNote", offset = 97)]
        [InputControl(name = "DonoNote098", displayName = "DonoNote D7", shortDisplayName = "DN D7", layout = "MidiNote", offset = 98)]
        [InputControl(name = "DonoNote099", displayName = "DonoNote D#7", shortDisplayName = "DN D#7", layout = "MidiNote", offset = 99)]
        [InputControl(name = "DonoNote100", displayName = "DonoNote E7", shortDisplayName = "DN E7", layout = "MidiNote", offset = 100)]
        [InputControl(name = "DonoNote101", displayName = "DonoNote F7", shortDisplayName = "DN F7", layout = "MidiNote", offset = 101)]
        [InputControl(name = "DonoNote102", displayName = "DonoNote F#7", shortDisplayName = "DN F#7", layout = "MidiNote", offset = 102)]
        [InputControl(name = "DonoNote103", displayName = "DonoNote G7", shortDisplayName = "DN G7", layout = "MidiNote", offset = 103)]
        [InputControl(name = "DonoNote104", displayName = "DonoNote G#7", shortDisplayName = "DN G#7", layout = "MidiNote", offset = 104)]
        [InputControl(name = "DonoNote105", displayName = "DonoNote A7", shortDisplayName = "DN A7", layout = "MidiNote", offset = 105)]
        [InputControl(name = "DonoNote106", displayName = "DonoNote A#7", shortDisplayName = "DN A#7", layout = "MidiNote", offset = 106)]
        [InputControl(name = "DonoNote107", displayName = "DonoNote B7", shortDisplayName = "DN B7", layout = "MidiNote", offset = 107)]
        [InputControl(name = "DonoNote108", displayName = "DonoNote C8", shortDisplayName = "DN C8", layout = "MidiNote", offset = 108)]
        [InputControl(name = "DonoNote109", displayName = "DonoNote C#8", shortDisplayName = "DN C#8", layout = "MidiNote", offset = 109)]
        [InputControl(name = "DonoNote110", displayName = "DonoNote D8", shortDisplayName = "DN D8", layout = "MidiNote", offset = 110)]
        [InputControl(name = "DonoNote111", displayName = "DonoNote D#8", shortDisplayName = "DN D#8", layout = "MidiNote", offset = 111)]
        [InputControl(name = "DonoNote112", displayName = "DonoNote E8", shortDisplayName = "DN E8", layout = "MidiNote", offset = 112)]
        [InputControl(name = "DonoNote113", displayName = "DonoNote F8", shortDisplayName = "DN F8", layout = "MidiNote", offset = 113)]
        [InputControl(name = "DonoNote114", displayName = "DonoNote F#8", shortDisplayName = "DN F#8", layout = "MidiNote", offset = 114)]
        [InputControl(name = "DonoNote115", displayName = "DonoNote G8", shortDisplayName = "DN G8", layout = "MidiNote", offset = 115)]
        [InputControl(name = "DonoNote116", displayName = "DonoNote G#8", shortDisplayName = "DN G#8", layout = "MidiNote", offset = 116)]
        [InputControl(name = "DonoNote117", displayName = "DonoNote A8", shortDisplayName = "DN A8", layout = "MidiNote", offset = 117)]
        [InputControl(name = "DonoNote118", displayName = "DonoNote A#8", shortDisplayName = "DN A#8", layout = "MidiNote", offset = 118)]
        [InputControl(name = "DonoNote119", displayName = "DonoNote B8", shortDisplayName = "DN B8", layout = "MidiNote", offset = 119)]
        [InputControl(name = "DonoNote120", displayName = "DonoNote C9", shortDisplayName = "DN C9", layout = "MidiNote", offset = 120)]
        [InputControl(name = "DonoNote121", displayName = "DonoNote C#9", shortDisplayName = "DN C#9", layout = "MidiNote", offset = 121)]
        [InputControl(name = "DonoNote122", displayName = "DonoNote D9", shortDisplayName = "DN D9", layout = "MidiNote", offset = 122)]
        [InputControl(name = "DonoNote123", displayName = "DonoNote D#9", shortDisplayName = "DN D#9", layout = "MidiNote", offset = 123)]
        [InputControl(name = "DonoNote124", displayName = "DonoNote E9", shortDisplayName = "DN E9", layout = "MidiNote", offset = 124)]
        [InputControl(name = "DonoNote125", displayName = "DonoNote F9", shortDisplayName = "DN F9", layout = "MidiNote", offset = 125)]
        [InputControl(name = "DonoNote126", displayName = "DonoNote F#9", shortDisplayName = "DN F#9", layout = "MidiNote", offset = 126)]
        [InputControl(name = "DonoNote127", displayName = "DonoNote G9", shortDisplayName = "DN G9", layout = "MidiNote", offset = 127)]
        public fixed byte donotes[128];
        #endregion
    }
}
