using System.Runtime.InteropServices;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Layouts;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.Utilities;

namespace Minis
{
    //
    // MIDI state struct with 128 notes and 128 controls
    //
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct MidiDeviceState : IInputStateTypeInfo
    {
        public FourCC format => new FourCC('D', 'I', 'D', 'I');

        #region Default ControlChanges
        [InputControl(name = "DonoControl000", displayName = "DonoControl 0"  , shortDisplayName = "DCC 0"  , layout = "MidiValue", offset = 1280)]
        [InputControl(name = "DonoControl001", displayName = "DonoControl 1"  , shortDisplayName = "DCC 1"  , layout = "MidiValue", offset = 1290)]
        [InputControl(name = "DonoControl002", displayName = "DonoControl 2"  , shortDisplayName = "DCC 2"  , layout = "MidiValue", offset = 1300)]
        [InputControl(name = "DonoControl003", displayName = "DonoControl 3"  , shortDisplayName = "DCC 3"  , layout = "MidiValue", offset = 1310)]
        [InputControl(name = "DonoControl004", displayName = "DonoControl 4"  , shortDisplayName = "DCC 4"  , layout = "MidiValue", offset = 1320)]
        [InputControl(name = "DonoControl005", displayName = "DonoControl 5"  , shortDisplayName = "DCC 5"  , layout = "MidiValue", offset = 1330)]
        [InputControl(name = "DonoControl006", displayName = "DonoControl 6"  , shortDisplayName = "DCC 6"  , layout = "MidiValue", offset = 1340)]
        [InputControl(name = "DonoControl007", displayName = "DonoControl 7"  , shortDisplayName = "DCC 7"  , layout = "MidiValue", offset = 1350)]
        [InputControl(name = "DonoControl008", displayName = "DonoControl 8"  , shortDisplayName = "DCC 8"  , layout = "MidiValue", offset = 1360)]
        [InputControl(name = "DonoControl009", displayName = "DonoControl 9"  , shortDisplayName = "DCC 9"  , layout = "MidiValue", offset = 1370)]
        [InputControl(name = "DonoControl010", displayName = "DonoControl 10" , shortDisplayName = "DCC 10" , layout = "MidiValue", offset = 1380)]
        [InputControl(name = "DonoControl011", displayName = "DonoControl 11" , shortDisplayName = "DCC 11" , layout = "MidiValue", offset = 1390)]
        [InputControl(name = "DonoControl012", displayName = "DonoControl 12" , shortDisplayName = "DCC 12" , layout = "MidiValue", offset = 1400)]
        [InputControl(name = "DonoControl013", displayName = "DonoControl 13" , shortDisplayName = "DCC 13" , layout = "MidiValue", offset = 1410)]
        [InputControl(name = "DonoControl014", displayName = "DonoControl 14" , shortDisplayName = "DCC 14" , layout = "MidiValue", offset = 1420)]
        [InputControl(name = "DonoControl015", displayName = "DonoControl 15" , shortDisplayName = "DCC 15" , layout = "MidiValue", offset = 1430)]
        [InputControl(name = "DonoControl016", displayName = "DonoControl 16" , shortDisplayName = "DCC 16" , layout = "MidiValue", offset = 1440)]
        [InputControl(name = "DonoControl017", displayName = "DonoControl 17" , shortDisplayName = "DCC 17" , layout = "MidiValue", offset = 1450)]
        [InputControl(name = "DonoControl018", displayName = "DonoControl 18" , shortDisplayName = "DCC 18" , layout = "MidiValue", offset = 1460)]
        [InputControl(name = "DonoControl019", displayName = "DonoControl 19" , shortDisplayName = "DCC 19" , layout = "MidiValue", offset = 1470)]
        [InputControl(name = "DonoControl020", displayName = "DonoControl 20" , shortDisplayName = "DCC 20" , layout = "MidiValue", offset = 1480)]
        [InputControl(name = "DonoControl021", displayName = "DonoControl 21" , shortDisplayName = "DCC 21" , layout = "MidiValue", offset = 1490)]
        [InputControl(name = "DonoControl022", displayName = "DonoControl 22" , shortDisplayName = "DCC 22" , layout = "MidiValue", offset = 1500)]
        [InputControl(name = "DonoControl023", displayName = "DonoControl 23" , shortDisplayName = "DCC 23" , layout = "MidiValue", offset = 1510)]
        [InputControl(name = "DonoControl024", displayName = "DonoControl 24" , shortDisplayName = "DCC 24" , layout = "MidiValue", offset = 1520)]
        [InputControl(name = "DonoControl025", displayName = "DonoControl 25" , shortDisplayName = "DCC 25" , layout = "MidiValue", offset = 1530)]
        [InputControl(name = "DonoControl026", displayName = "DonoControl 26" , shortDisplayName = "DCC 26" , layout = "MidiValue", offset = 1540)]
        [InputControl(name = "DonoControl027", displayName = "DonoControl 27" , shortDisplayName = "DCC 27" , layout = "MidiValue", offset = 1550)]
        [InputControl(name = "DonoControl028", displayName = "DonoControl 28" , shortDisplayName = "DCC 28" , layout = "MidiValue", offset = 1560)]
        [InputControl(name = "DonoControl029", displayName = "DonoControl 29" , shortDisplayName = "DCC 29" , layout = "MidiValue", offset = 1570)]
        [InputControl(name = "DonoControl030", displayName = "DonoControl 30" , shortDisplayName = "DCC 30" , layout = "MidiValue", offset = 1580)]
        [InputControl(name = "DonoControl031", displayName = "DonoControl 31" , shortDisplayName = "DCC 31" , layout = "MidiValue", offset = 1590)]
        [InputControl(name = "DonoControl032", displayName = "DonoControl 32" , shortDisplayName = "DCC 32" , layout = "MidiValue", offset = 1600)]
        [InputControl(name = "DonoControl033", displayName = "DonoControl 33" , shortDisplayName = "DCC 33" , layout = "MidiValue", offset = 1610)]
        [InputControl(name = "DonoControl034", displayName = "DonoControl 34" , shortDisplayName = "DCC 34" , layout = "MidiValue", offset = 1620)]
        [InputControl(name = "DonoControl035", displayName = "DonoControl 35" , shortDisplayName = "DCC 35" , layout = "MidiValue", offset = 1630)]
        [InputControl(name = "DonoControl036", displayName = "DonoControl 36" , shortDisplayName = "DCC 36" , layout = "MidiValue", offset = 1640)]
        [InputControl(name = "DonoControl037", displayName = "DonoControl 37" , shortDisplayName = "DCC 37" , layout = "MidiValue", offset = 1650)]
        [InputControl(name = "DonoControl038", displayName = "DonoControl 38" , shortDisplayName = "DCC 38" , layout = "MidiValue", offset = 1660)]
        [InputControl(name = "DonoControl039", displayName = "DonoControl 39" , shortDisplayName = "DCC 39" , layout = "MidiValue", offset = 1670)]
        [InputControl(name = "DonoControl040", displayName = "DonoControl 40" , shortDisplayName = "DCC 40" , layout = "MidiValue", offset = 1680)]
        [InputControl(name = "DonoControl041", displayName = "DonoControl 41" , shortDisplayName = "DCC 41" , layout = "MidiValue", offset = 1690)]
        [InputControl(name = "DonoControl042", displayName = "DonoControl 42" , shortDisplayName = "DCC 42" , layout = "MidiValue", offset = 1700)]
        [InputControl(name = "DonoControl043", displayName = "DonoControl 43" , shortDisplayName = "DCC 43" , layout = "MidiValue", offset = 1710)]
        [InputControl(name = "DonoControl044", displayName = "DonoControl 44" , shortDisplayName = "DCC 44" , layout = "MidiValue", offset = 1720)]
        [InputControl(name = "DonoControl045", displayName = "DonoControl 45" , shortDisplayName = "DCC 45" , layout = "MidiValue", offset = 1730)]
        [InputControl(name = "DonoControl046", displayName = "DonoControl 46" , shortDisplayName = "DCC 46" , layout = "MidiValue", offset = 1740)]
        [InputControl(name = "DonoControl047", displayName = "DonoControl 47" , shortDisplayName = "DCC 47" , layout = "MidiValue", offset = 1750)]
        [InputControl(name = "DonoControl048", displayName = "DonoControl 48" , shortDisplayName = "DCC 48" , layout = "MidiValue", offset = 1760)]
        [InputControl(name = "DonoControl049", displayName = "DonoControl 49" , shortDisplayName = "DCC 49" , layout = "MidiValue", offset = 1770)]
        [InputControl(name = "DonoControl050", displayName = "DonoControl 50" , shortDisplayName = "DCC 50" , layout = "MidiValue", offset = 1780)]
        [InputControl(name = "DonoControl051", displayName = "DonoControl 51" , shortDisplayName = "DCC 51" , layout = "MidiValue", offset = 1790)]
        [InputControl(name = "DonoControl052", displayName = "DonoControl 52" , shortDisplayName = "DCC 52" , layout = "MidiValue", offset = 1800)]
        [InputControl(name = "DonoControl053", displayName = "DonoControl 53" , shortDisplayName = "DCC 53" , layout = "MidiValue", offset = 1810)]
        [InputControl(name = "DonoControl054", displayName = "DonoControl 54" , shortDisplayName = "DCC 54" , layout = "MidiValue", offset = 1820)]
        [InputControl(name = "DonoControl055", displayName = "DonoControl 55" , shortDisplayName = "DCC 55" , layout = "MidiValue", offset = 1830)]
        [InputControl(name = "DonoControl056", displayName = "DonoControl 56" , shortDisplayName = "DCC 56" , layout = "MidiValue", offset = 1840)]
        [InputControl(name = "DonoControl057", displayName = "DonoControl 57" , shortDisplayName = "DCC 57" , layout = "MidiValue", offset = 1850)]
        [InputControl(name = "DonoControl058", displayName = "DonoControl 58" , shortDisplayName = "DCC 58" , layout = "MidiValue", offset = 1860)]
        [InputControl(name = "DonoControl059", displayName = "DonoControl 59" , shortDisplayName = "DCC 59" , layout = "MidiValue", offset = 1870)]
        [InputControl(name = "DonoControl060", displayName = "DonoControl 60" , shortDisplayName = "DCC 60" , layout = "MidiValue", offset = 1880)]
        [InputControl(name = "DonoControl061", displayName = "DonoControl 61" , shortDisplayName = "DCC 61" , layout = "MidiValue", offset = 1890)]
        [InputControl(name = "DonoControl062", displayName = "DonoControl 62" , shortDisplayName = "DCC 62" , layout = "MidiValue", offset = 1900)]
        [InputControl(name = "DonoControl063", displayName = "DonoControl 63" , shortDisplayName = "DCC 63" , layout = "MidiValue", offset = 1910)]
        [InputControl(name = "DonoControl064", displayName = "DonoControl 64" , shortDisplayName = "DCC 64" , layout = "MidiValue", offset = 1920)]
        [InputControl(name = "DonoControl065", displayName = "DonoControl 65" , shortDisplayName = "DCC 65" , layout = "MidiValue", offset = 1930)]
        [InputControl(name = "DonoControl066", displayName = "DonoControl 66" , shortDisplayName = "DCC 66" , layout = "MidiValue", offset = 1940)]
        [InputControl(name = "DonoControl067", displayName = "DonoControl 67" , shortDisplayName = "DCC 67" , layout = "MidiValue", offset = 1950)]
        [InputControl(name = "DonoControl068", displayName = "DonoControl 68" , shortDisplayName = "DCC 68" , layout = "MidiValue", offset = 1960)]
        [InputControl(name = "DonoControl069", displayName = "DonoControl 69" , shortDisplayName = "DCC 69" , layout = "MidiValue", offset = 1970)]
        [InputControl(name = "DonoControl070", displayName = "DonoControl 70" , shortDisplayName = "DCC 70" , layout = "MidiValue", offset = 1980)]
        [InputControl(name = "DonoControl071", displayName = "DonoControl 71" , shortDisplayName = "DCC 71" , layout = "MidiValue", offset = 1990)]
        [InputControl(name = "DonoControl072", displayName = "DonoControl 72" , shortDisplayName = "DCC 72" , layout = "MidiValue", offset = 2000)]
        [InputControl(name = "DonoControl073", displayName = "DonoControl 73" , shortDisplayName = "DCC 73" , layout = "MidiValue", offset = 2010)]
        [InputControl(name = "DonoControl074", displayName = "DonoControl 74" , shortDisplayName = "DCC 74" , layout = "MidiValue", offset = 2020)]
        [InputControl(name = "DonoControl075", displayName = "DonoControl 75" , shortDisplayName = "DCC 75" , layout = "MidiValue", offset = 2030)]
        [InputControl(name = "DonoControl076", displayName = "DonoControl 76" , shortDisplayName = "DCC 76" , layout = "MidiValue", offset = 2040)]
        [InputControl(name = "DonoControl077", displayName = "DonoControl 77" , shortDisplayName = "DCC 77" , layout = "MidiValue", offset = 2050)]
        [InputControl(name = "DonoControl078", displayName = "DonoControl 78" , shortDisplayName = "DCC 78" , layout = "MidiValue", offset = 2060)]
        [InputControl(name = "DonoControl079", displayName = "DonoControl 79" , shortDisplayName = "DCC 79" , layout = "MidiValue", offset = 2070)]
        [InputControl(name = "DonoControl080", displayName = "DonoControl 80" , shortDisplayName = "DCC 80" , layout = "MidiValue", offset = 2080)]
        [InputControl(name = "DonoControl081", displayName = "DonoControl 81" , shortDisplayName = "DCC 81" , layout = "MidiValue", offset = 2090)]
        [InputControl(name = "DonoControl082", displayName = "DonoControl 82" , shortDisplayName = "DCC 82" , layout = "MidiValue", offset = 2100)]
        [InputControl(name = "DonoControl083", displayName = "DonoControl 83" , shortDisplayName = "DCC 83" , layout = "MidiValue", offset = 2110)]
        [InputControl(name = "DonoControl084", displayName = "DonoControl 84" , shortDisplayName = "DCC 84" , layout = "MidiValue", offset = 2120)]
        [InputControl(name = "DonoControl085", displayName = "DonoControl 85" , shortDisplayName = "DCC 85" , layout = "MidiValue", offset = 2130)]
        [InputControl(name = "DonoControl086", displayName = "DonoControl 86" , shortDisplayName = "DCC 86" , layout = "MidiValue", offset = 2140)]
        [InputControl(name = "DonoControl087", displayName = "DonoControl 87" , shortDisplayName = "DCC 87" , layout = "MidiValue", offset = 2150)]
        [InputControl(name = "DonoControl088", displayName = "DonoControl 88" , shortDisplayName = "DCC 88" , layout = "MidiValue", offset = 2160)]
        [InputControl(name = "DonoControl089", displayName = "DonoControl 89" , shortDisplayName = "DCC 89" , layout = "MidiValue", offset = 2170)]
        [InputControl(name = "DonoControl090", displayName = "DonoControl 90" , shortDisplayName = "DCC 90" , layout = "MidiValue", offset = 2180)]
        [InputControl(name = "DonoControl091", displayName = "DonoControl 91" , shortDisplayName = "DCC 91" , layout = "MidiValue", offset = 2190)]
        [InputControl(name = "DonoControl092", displayName = "DonoControl 92" , shortDisplayName = "DCC 92" , layout = "MidiValue", offset = 2200)]
        [InputControl(name = "DonoControl093", displayName = "DonoControl 93" , shortDisplayName = "DCC 93" , layout = "MidiValue", offset = 2210)]
        [InputControl(name = "DonoControl094", displayName = "DonoControl 94" , shortDisplayName = "DCC 94" , layout = "MidiValue", offset = 2220)]
        [InputControl(name = "DonoControl095", displayName = "DonoControl 95" , shortDisplayName = "DCC 95" , layout = "MidiValue", offset = 2230)]
        [InputControl(name = "DonoControl096", displayName = "DonoControl 96" , shortDisplayName = "DCC 96" , layout = "MidiValue", offset = 2240)]
        [InputControl(name = "DonoControl097", displayName = "DonoControl 97" , shortDisplayName = "DCC 97" , layout = "MidiValue", offset = 2250)]
        [InputControl(name = "DonoControl098", displayName = "DonoControl 98" , shortDisplayName = "DCC 98" , layout = "MidiValue", offset = 2260)]
        [InputControl(name = "DonoControl099", displayName = "DonoControl 99" , shortDisplayName = "DCC 99" , layout = "MidiValue", offset = 2270)]
        [InputControl(name = "DonoControl100", displayName = "DonoControl 100", shortDisplayName = "DCC 100", layout = "MidiValue", offset = 2280)]
        [InputControl(name = "DonoControl101", displayName = "DonoControl 101", shortDisplayName = "DCC 101", layout = "MidiValue", offset = 2290)]
        [InputControl(name = "DonoControl102", displayName = "DonoControl 102", shortDisplayName = "DCC 102", layout = "MidiValue", offset = 2300)]
        [InputControl(name = "DonoControl103", displayName = "DonoControl 103", shortDisplayName = "DCC 103", layout = "MidiValue", offset = 2310)]
        [InputControl(name = "DonoControl104", displayName = "DonoControl 104", shortDisplayName = "DCC 104", layout = "MidiValue", offset = 2320)]
        [InputControl(name = "DonoControl105", displayName = "DonoControl 105", shortDisplayName = "DCC 105", layout = "MidiValue", offset = 2330)]
        [InputControl(name = "DonoControl106", displayName = "DonoControl 106", shortDisplayName = "DCC 106", layout = "MidiValue", offset = 2340)]
        [InputControl(name = "DonoControl107", displayName = "DonoControl 107", shortDisplayName = "DCC 107", layout = "MidiValue", offset = 2350)]
        [InputControl(name = "DonoControl108", displayName = "DonoControl 108", shortDisplayName = "DCC 108", layout = "MidiValue", offset = 2360)]
        [InputControl(name = "DonoControl109", displayName = "DonoControl 109", shortDisplayName = "DCC 109", layout = "MidiValue", offset = 2370)]
        [InputControl(name = "DonoControl110", displayName = "DonoControl 110", shortDisplayName = "DCC 110", layout = "MidiValue", offset = 2380)]
        [InputControl(name = "DonoControl111", displayName = "DonoControl 111", shortDisplayName = "DCC 111", layout = "MidiValue", offset = 2390)]
        [InputControl(name = "DonoControl112", displayName = "DonoControl 112", shortDisplayName = "DCC 112", layout = "MidiValue", offset = 2400)]
        [InputControl(name = "DonoControl113", displayName = "DonoControl 113", shortDisplayName = "DCC 113", layout = "MidiValue", offset = 2410)]
        [InputControl(name = "DonoControl114", displayName = "DonoControl 114", shortDisplayName = "DCC 114", layout = "MidiValue", offset = 2420)]
        [InputControl(name = "DonoControl115", displayName = "DonoControl 115", shortDisplayName = "DCC 115", layout = "MidiValue", offset = 2430)]
        [InputControl(name = "DonoControl116", displayName = "DonoControl 116", shortDisplayName = "DCC 116", layout = "MidiValue", offset = 2440)]
        [InputControl(name = "DonoControl117", displayName = "DonoControl 117", shortDisplayName = "DCC 117", layout = "MidiValue", offset = 2450)]
        [InputControl(name = "DonoControl118", displayName = "DonoControl 118", shortDisplayName = "DCC 118", layout = "MidiValue", offset = 2460)]
        [InputControl(name = "DonoControl119", displayName = "DonoControl 119", shortDisplayName = "DCC 119", layout = "MidiValue", offset = 2470)]
        [InputControl(name = "DonoControl120", displayName = "DonoControl 120", shortDisplayName = "DCC 120", layout = "MidiValue", offset = 2480)]
        [InputControl(name = "DonoControl121", displayName = "DonoControl 121", shortDisplayName = "DCC 121", layout = "MidiValue", offset = 2490)]
        [InputControl(name = "DonoControl122", displayName = "DonoControl 122", shortDisplayName = "DCC 122", layout = "MidiValue", offset = 2500)]
        [InputControl(name = "DonoControl123", displayName = "DonoControl 123", shortDisplayName = "DCC 123", layout = "MidiValue", offset = 2510)]
        [InputControl(name = "DonoControl124", displayName = "DonoControl 124", shortDisplayName = "DCC 124", layout = "MidiValue", offset = 2520)]
        [InputControl(name = "DonoControl125", displayName = "DonoControl 125", shortDisplayName = "DCC 125", layout = "MidiValue", offset = 2530)]
        [InputControl(name = "DonoControl126", displayName = "DonoControl 126", shortDisplayName = "DCC 126", layout = "MidiValue", offset = 2540)]
        [InputControl(name = "DonoControl127", displayName = "DonoControl 127", shortDisplayName = "DCC 127", layout = "MidiValue", offset = 2550)]
        public fixed byte controls[128];
        #endregion

        #region Dono Notes
        [InputControl(name = "DonoNote000", displayName = "DonoNote C -1", shortDisplayName = "DN C -1", layout = "MidiNote", offset = 0000)]
        [InputControl(name = "DonoNote001", displayName = "DonoNote C#-1", shortDisplayName = "DN C#-1", layout = "MidiNote", offset = 0010)]
        [InputControl(name = "DonoNote002", displayName = "DonoNote D -1", shortDisplayName = "DN D -1", layout = "MidiNote", offset = 0020)]
        [InputControl(name = "DonoNote003", displayName = "DonoNote D#-1", shortDisplayName = "DN D#-1", layout = "MidiNote", offset = 0030)]
        [InputControl(name = "DonoNote004", displayName = "DonoNote E -1", shortDisplayName = "DN E -1", layout = "MidiNote", offset = 0040)]
        [InputControl(name = "DonoNote005", displayName = "DonoNote F -1", shortDisplayName = "DN F -1", layout = "MidiNote", offset = 0050)]
        [InputControl(name = "DonoNote006", displayName = "DonoNote F#-1", shortDisplayName = "DN F#-1", layout = "MidiNote", offset = 0060)]
        [InputControl(name = "DonoNote007", displayName = "DonoNote G -1", shortDisplayName = "DN G -1", layout = "MidiNote", offset = 0070)]
        [InputControl(name = "DonoNote008", displayName = "DonoNote G#-1", shortDisplayName = "DN G#-1", layout = "MidiNote", offset = 0080)]
        [InputControl(name = "DonoNote009", displayName = "DonoNote A -1", shortDisplayName = "DN A -1", layout = "MidiNote", offset = 0090)]
        [InputControl(name = "DonoNote010", displayName = "DonoNote A#-1", shortDisplayName = "DN A#-1", layout = "MidiNote", offset = 0100)]
        [InputControl(name = "DonoNote011", displayName = "DonoNote B -1", shortDisplayName = "DN B -1", layout = "MidiNote", offset = 0110)]
        [InputControl(name = "DonoNote012", displayName = "DonoNote C  0", shortDisplayName = "DN C  0", layout = "MidiNote", offset = 0120)]
        [InputControl(name = "DonoNote013", displayName = "DonoNote C# 0", shortDisplayName = "DN C# 0", layout = "MidiNote", offset = 0130)]
        [InputControl(name = "DonoNote014", displayName = "DonoNote D  0", shortDisplayName = "DN D  0", layout = "MidiNote", offset = 0140)]
        [InputControl(name = "DonoNote015", displayName = "DonoNote D# 0", shortDisplayName = "DN D# 0", layout = "MidiNote", offset = 0150)]
        [InputControl(name = "DonoNote016", displayName = "DonoNote E  0", shortDisplayName = "DN E  0", layout = "MidiNote", offset = 0160)]
        [InputControl(name = "DonoNote017", displayName = "DonoNote F  0", shortDisplayName = "DN F  0", layout = "MidiNote", offset = 0170)]
        [InputControl(name = "DonoNote018", displayName = "DonoNote F# 0", shortDisplayName = "DN F# 0", layout = "MidiNote", offset = 0180)]
        [InputControl(name = "DonoNote019", displayName = "DonoNote G  0", shortDisplayName = "DN G  0", layout = "MidiNote", offset = 0190)]
        [InputControl(name = "DonoNote020", displayName = "DonoNote G# 0", shortDisplayName = "DN G# 0", layout = "MidiNote", offset = 0200)]
        [InputControl(name = "DonoNote021", displayName = "DonoNote A  0", shortDisplayName = "DN A  0", layout = "MidiNote", offset = 0210)]
        [InputControl(name = "DonoNote022", displayName = "DonoNote A# 0", shortDisplayName = "DN A# 0", layout = "MidiNote", offset = 0220)]
        [InputControl(name = "DonoNote023", displayName = "DonoNote B  0", shortDisplayName = "DN B  0", layout = "MidiNote", offset = 0230)]
        [InputControl(name = "DonoNote024", displayName = "DonoNote C  1", shortDisplayName = "DN C  1", layout = "MidiNote", offset = 0240)]
        [InputControl(name = "DonoNote025", displayName = "DonoNote C# 1", shortDisplayName = "DN C# 1", layout = "MidiNote", offset = 0250)]
        [InputControl(name = "DonoNote026", displayName = "DonoNote D  1", shortDisplayName = "DN D  1", layout = "MidiNote", offset = 0260)]
        [InputControl(name = "DonoNote027", displayName = "DonoNote D# 1", shortDisplayName = "DN D# 1", layout = "MidiNote", offset = 0270)]
        [InputControl(name = "DonoNote028", displayName = "DonoNote E  1", shortDisplayName = "DN E  1", layout = "MidiNote", offset = 0280)]
        [InputControl(name = "DonoNote029", displayName = "DonoNote F  1", shortDisplayName = "DN F  1", layout = "MidiNote", offset = 0290)]
        [InputControl(name = "DonoNote030", displayName = "DonoNote F# 1", shortDisplayName = "DN F# 1", layout = "MidiNote", offset = 0300)]
        [InputControl(name = "DonoNote031", displayName = "DonoNote G  1", shortDisplayName = "DN G  1", layout = "MidiNote", offset = 0310)]
        [InputControl(name = "DonoNote032", displayName = "DonoNote G# 1", shortDisplayName = "DN G# 1", layout = "MidiNote", offset = 0320)]
        [InputControl(name = "DonoNote033", displayName = "DonoNote A  1", shortDisplayName = "DN A  1", layout = "MidiNote", offset = 0330)]
        [InputControl(name = "DonoNote034", displayName = "DonoNote A# 1", shortDisplayName = "DN A# 1", layout = "MidiNote", offset = 0340)]
        [InputControl(name = "DonoNote035", displayName = "DonoNote B  1", shortDisplayName = "DN B  1", layout = "MidiNote", offset = 0350)]
        [InputControl(name = "DonoNote036", displayName = "DonoNote C  2", shortDisplayName = "DN C  2", layout = "MidiNote", offset = 0360)]
        [InputControl(name = "DonoNote037", displayName = "DonoNote C# 2", shortDisplayName = "DN C# 2", layout = "MidiNote", offset = 0370)]
        [InputControl(name = "DonoNote038", displayName = "DonoNote D  2", shortDisplayName = "DN D  2", layout = "MidiNote", offset = 0380)]
        [InputControl(name = "DonoNote039", displayName = "DonoNote D# 2", shortDisplayName = "DN D# 2", layout = "MidiNote", offset = 0390)]
        [InputControl(name = "DonoNote040", displayName = "DonoNote E  2", shortDisplayName = "DN E  2", layout = "MidiNote", offset = 0400)]
        [InputControl(name = "DonoNote041", displayName = "DonoNote F  2", shortDisplayName = "DN F  2", layout = "MidiNote", offset = 0410)]
        [InputControl(name = "DonoNote042", displayName = "DonoNote F# 2", shortDisplayName = "DN F# 2", layout = "MidiNote", offset = 0420)]
        [InputControl(name = "DonoNote043", displayName = "DonoNote G  2", shortDisplayName = "DN G  2", layout = "MidiNote", offset = 0430)]
        [InputControl(name = "DonoNote044", displayName = "DonoNote G# 2", shortDisplayName = "DN G# 2", layout = "MidiNote", offset = 0440)]
        [InputControl(name = "DonoNote045", displayName = "DonoNote A  2", shortDisplayName = "DN A  2", layout = "MidiNote", offset = 0450)]
        [InputControl(name = "DonoNote046", displayName = "DonoNote A# 2", shortDisplayName = "DN A# 2", layout = "MidiNote", offset = 0460)]
        [InputControl(name = "DonoNote047", displayName = "DonoNote B  2", shortDisplayName = "DN B  2", layout = "MidiNote", offset = 0470)]
        [InputControl(name = "DonoNote048", displayName = "DonoNote C  3", shortDisplayName = "DN C  3", layout = "MidiNote", offset = 0480)]
        [InputControl(name = "DonoNote049", displayName = "DonoNote C# 3", shortDisplayName = "DN C# 3", layout = "MidiNote", offset = 0490)]
        [InputControl(name = "DonoNote050", displayName = "DonoNote D  3", shortDisplayName = "DN D  3", layout = "MidiNote", offset = 0500)]
        [InputControl(name = "DonoNote051", displayName = "DonoNote D# 3", shortDisplayName = "DN D# 3", layout = "MidiNote", offset = 0510)]
        [InputControl(name = "DonoNote052", displayName = "DonoNote E  3", shortDisplayName = "DN E  3", layout = "MidiNote", offset = 0520)]
        [InputControl(name = "DonoNote053", displayName = "DonoNote F  3", shortDisplayName = "DN F  3", layout = "MidiNote", offset = 0530)]
        [InputControl(name = "DonoNote054", displayName = "DonoNote F# 3", shortDisplayName = "DN F# 3", layout = "MidiNote", offset = 0540)]
        [InputControl(name = "DonoNote055", displayName = "DonoNote G  3", shortDisplayName = "DN G  3", layout = "MidiNote", offset = 0550)]
        [InputControl(name = "DonoNote056", displayName = "DonoNote G# 3", shortDisplayName = "DN G# 3", layout = "MidiNote", offset = 0560)]
        [InputControl(name = "DonoNote057", displayName = "DonoNote A  3", shortDisplayName = "DN A  3", layout = "MidiNote", offset = 0570)]
        [InputControl(name = "DonoNote058", displayName = "DonoNote A# 3", shortDisplayName = "DN A# 3", layout = "MidiNote", offset = 0580)]
        [InputControl(name = "DonoNote059", displayName = "DonoNote B  3", shortDisplayName = "DN B  3", layout = "MidiNote", offset = 0590)]
        [InputControl(name = "DonoNote060", displayName = "DonoNote C  4", shortDisplayName = "DN C  4", layout = "MidiNote", offset = 0600)]
        [InputControl(name = "DonoNote061", displayName = "DonoNote C# 4", shortDisplayName = "DN C# 4", layout = "MidiNote", offset = 0610)]
        [InputControl(name = "DonoNote062", displayName = "DonoNote D  4", shortDisplayName = "DN D  4", layout = "MidiNote", offset = 0620)]
        [InputControl(name = "DonoNote063", displayName = "DonoNote D# 4", shortDisplayName = "DN D# 4", layout = "MidiNote", offset = 0630)]
        [InputControl(name = "DonoNote064", displayName = "DonoNote E  4", shortDisplayName = "DN E  4", layout = "MidiNote", offset = 0640)]
        [InputControl(name = "DonoNote065", displayName = "DonoNote F  4", shortDisplayName = "DN F  4", layout = "MidiNote", offset = 0650)]
        [InputControl(name = "DonoNote066", displayName = "DonoNote F# 4", shortDisplayName = "DN F# 4", layout = "MidiNote", offset = 0660)]
        [InputControl(name = "DonoNote067", displayName = "DonoNote G  4", shortDisplayName = "DN G  4", layout = "MidiNote", offset = 0670)]
        [InputControl(name = "DonoNote068", displayName = "DonoNote G# 4", shortDisplayName = "DN G# 4", layout = "MidiNote", offset = 0680)]
        [InputControl(name = "DonoNote069", displayName = "DonoNote A  4", shortDisplayName = "DN A  4", layout = "MidiNote", offset = 0690)]
        [InputControl(name = "DonoNote070", displayName = "DonoNote A# 4", shortDisplayName = "DN A# 4", layout = "MidiNote", offset = 0700)]
        [InputControl(name = "DonoNote071", displayName = "DonoNote B  4", shortDisplayName = "DN B  4", layout = "MidiNote", offset = 0710)]
        [InputControl(name = "DonoNote072", displayName = "DonoNote C  5", shortDisplayName = "DN C  5", layout = "MidiNote", offset = 0720)]
        [InputControl(name = "DonoNote073", displayName = "DonoNote C# 5", shortDisplayName = "DN C# 5", layout = "MidiNote", offset = 0730)]
        [InputControl(name = "DonoNote074", displayName = "DonoNote D  5", shortDisplayName = "DN D  5", layout = "MidiNote", offset = 0740)]
        [InputControl(name = "DonoNote075", displayName = "DonoNote D# 5", shortDisplayName = "DN D# 5", layout = "MidiNote", offset = 0750)]
        [InputControl(name = "DonoNote076", displayName = "DonoNote E  5", shortDisplayName = "DN E  5", layout = "MidiNote", offset = 0760)]
        [InputControl(name = "DonoNote077", displayName = "DonoNote F  5", shortDisplayName = "DN F  5", layout = "MidiNote", offset = 0770)]
        [InputControl(name = "DonoNote078", displayName = "DonoNote F# 5", shortDisplayName = "DN F# 5", layout = "MidiNote", offset = 0780)]
        [InputControl(name = "DonoNote079", displayName = "DonoNote G  5", shortDisplayName = "DN G  5", layout = "MidiNote", offset = 0790)]
        [InputControl(name = "DonoNote080", displayName = "DonoNote G# 5", shortDisplayName = "DN G# 5", layout = "MidiNote", offset = 0800)]
        [InputControl(name = "DonoNote081", displayName = "DonoNote A  5", shortDisplayName = "DN A  5", layout = "MidiNote", offset = 0810)]
        [InputControl(name = "DonoNote082", displayName = "DonoNote A# 5", shortDisplayName = "DN A# 5", layout = "MidiNote", offset = 0820)]
        [InputControl(name = "DonoNote083", displayName = "DonoNote B  5", shortDisplayName = "DN B  5", layout = "MidiNote", offset = 0830)]
        [InputControl(name = "DonoNote084", displayName = "DonoNote C  6", shortDisplayName = "DN C  6", layout = "MidiNote", offset = 0840)]
        [InputControl(name = "DonoNote085", displayName = "DonoNote C# 6", shortDisplayName = "DN C# 6", layout = "MidiNote", offset = 0850)]
        [InputControl(name = "DonoNote086", displayName = "DonoNote D  6", shortDisplayName = "DN D  6", layout = "MidiNote", offset = 0860)]
        [InputControl(name = "DonoNote087", displayName = "DonoNote D# 6", shortDisplayName = "DN D# 6", layout = "MidiNote", offset = 0870)]
        [InputControl(name = "DonoNote088", displayName = "DonoNote E  6", shortDisplayName = "DN E  6", layout = "MidiNote", offset = 0880)]
        [InputControl(name = "DonoNote089", displayName = "DonoNote F  6", shortDisplayName = "DN F  6", layout = "MidiNote", offset = 0890)]
        [InputControl(name = "DonoNote090", displayName = "DonoNote F# 6", shortDisplayName = "DN F# 6", layout = "MidiNote", offset = 0900)]
        [InputControl(name = "DonoNote091", displayName = "DonoNote G  6", shortDisplayName = "DN G  6", layout = "MidiNote", offset = 0910)]
        [InputControl(name = "DonoNote092", displayName = "DonoNote G# 6", shortDisplayName = "DN G# 6", layout = "MidiNote", offset = 0920)]
        [InputControl(name = "DonoNote093", displayName = "DonoNote A  6", shortDisplayName = "DN A  6", layout = "MidiNote", offset = 0930)]
        [InputControl(name = "DonoNote094", displayName = "DonoNote A# 6", shortDisplayName = "DN A# 6", layout = "MidiNote", offset = 0940)]
        [InputControl(name = "DonoNote095", displayName = "DonoNote B  6", shortDisplayName = "DN B  6", layout = "MidiNote", offset = 0950)]
        [InputControl(name = "DonoNote096", displayName = "DonoNote C  7", shortDisplayName = "DN C  7", layout = "MidiNote", offset = 0960)]
        [InputControl(name = "DonoNote097", displayName = "DonoNote C# 7", shortDisplayName = "DN C# 7", layout = "MidiNote", offset = 0970)]
        [InputControl(name = "DonoNote098", displayName = "DonoNote D  7", shortDisplayName = "DN D  7", layout = "MidiNote", offset = 0980)]
        [InputControl(name = "DonoNote099", displayName = "DonoNote D# 7", shortDisplayName = "DN D# 7", layout = "MidiNote", offset = 0990)]
        [InputControl(name = "DonoNote100", displayName = "DonoNote E  7", shortDisplayName = "DN E  7", layout = "MidiNote", offset = 1000)]
        [InputControl(name = "DonoNote101", displayName = "DonoNote F  7", shortDisplayName = "DN F  7", layout = "MidiNote", offset = 1010)]
        [InputControl(name = "DonoNote102", displayName = "DonoNote F# 7", shortDisplayName = "DN F# 7", layout = "MidiNote", offset = 1020)]
        [InputControl(name = "DonoNote103", displayName = "DonoNote G  7", shortDisplayName = "DN G  7", layout = "MidiNote", offset = 1030)]
        [InputControl(name = "DonoNote104", displayName = "DonoNote G# 7", shortDisplayName = "DN G# 7", layout = "MidiNote", offset = 1040)]
        [InputControl(name = "DonoNote105", displayName = "DonoNote A  7", shortDisplayName = "DN A  7", layout = "MidiNote", offset = 1050)]
        [InputControl(name = "DonoNote106", displayName = "DonoNote A# 7", shortDisplayName = "DN A# 7", layout = "MidiNote", offset = 1060)]
        [InputControl(name = "DonoNote107", displayName = "DonoNote B  7", shortDisplayName = "DN B  7", layout = "MidiNote", offset = 1070)]
        [InputControl(name = "DonoNote108", displayName = "DonoNote C  8", shortDisplayName = "DN C  8", layout = "MidiNote", offset = 1080)]
        [InputControl(name = "DonoNote109", displayName = "DonoNote C# 8", shortDisplayName = "DN C# 8", layout = "MidiNote", offset = 1090)]
        [InputControl(name = "DonoNote110", displayName = "DonoNote D  8", shortDisplayName = "DN D  8", layout = "MidiNote", offset = 1100)]
        [InputControl(name = "DonoNote111", displayName = "DonoNote D# 8", shortDisplayName = "DN D# 8", layout = "MidiNote", offset = 1110)]
        [InputControl(name = "DonoNote112", displayName = "DonoNote E  8", shortDisplayName = "DN E  8", layout = "MidiNote", offset = 1120)]
        [InputControl(name = "DonoNote113", displayName = "DonoNote F  8", shortDisplayName = "DN F  8", layout = "MidiNote", offset = 1130)]
        [InputControl(name = "DonoNote114", displayName = "DonoNote F# 8", shortDisplayName = "DN F# 8", layout = "MidiNote", offset = 1140)]
        [InputControl(name = "DonoNote115", displayName = "DonoNote G  8", shortDisplayName = "DN G  8", layout = "MidiNote", offset = 1150)]
        [InputControl(name = "DonoNote116", displayName = "DonoNote G# 8", shortDisplayName = "DN G# 8", layout = "MidiNote", offset = 1160)]
        [InputControl(name = "DonoNote117", displayName = "DonoNote A  8", shortDisplayName = "DN A  8", layout = "MidiNote", offset = 1170)]
        [InputControl(name = "DonoNote118", displayName = "DonoNote A# 8", shortDisplayName = "DN A# 8", layout = "MidiNote", offset = 1180)]
        [InputControl(name = "DonoNote119", displayName = "DonoNote B  8", shortDisplayName = "DN B  8", layout = "MidiNote", offset = 1190)]
        [InputControl(name = "DonoNote120", displayName = "DonoNote C  9", shortDisplayName = "DN C  9", layout = "MidiNote", offset = 1200)]
        [InputControl(name = "DonoNote121", displayName = "DonoNote C# 9", shortDisplayName = "DN C# 9", layout = "MidiNote", offset = 1210)]
        [InputControl(name = "DonoNote122", displayName = "DonoNote D  9", shortDisplayName = "DN D  9", layout = "MidiNote", offset = 1220)]
        [InputControl(name = "DonoNote123", displayName = "DonoNote D# 9", shortDisplayName = "DN D# 9", layout = "MidiNote", offset = 1230)]
        [InputControl(name = "DonoNote124", displayName = "DonoNote E  9", shortDisplayName = "DN E  9", layout = "MidiNote", offset = 1240)]
        [InputControl(name = "DonoNote125", displayName = "DonoNote F  9", shortDisplayName = "DN F  9", layout = "MidiNote", offset = 1250)]
        [InputControl(name = "DonoNote126", displayName = "DonoNote F# 9", shortDisplayName = "DN F# 9", layout = "MidiNote", offset = 1260)]
        [InputControl(name = "DonoNote127", displayName = "DonoNote G  9", shortDisplayName = "DN G  9", layout = "MidiNote", offset = 1270)]
        public fixed byte donotes[128];
        #endregion

        [InputControl(name = "PitchBend", displayName = "PitchBend", shortDisplayName = "Pitch", layout = "MidiPitch", offset = 2560)]
        public fixed byte pitchBned[1];
        [InputControl(name = "PitchUp", displayName = "PitchBendUp", shortDisplayName = "PitchUp", layout = "MidiPitchUp", offset = 2570)]
        public fixed byte pitchUp[1];
        [InputControl(name = "PitchDown", displayName = "PitchBendDown", shortDisplayName = "PitchDown", layout = "MidiPitchDown", offset = 2580)]
        public fixed byte pitchDown[1];
    }
}
