using System.Runtime.InteropServices;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Layouts;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.Utilities;

namespace Minis.Runtime.MidiVector3Device
{
    //
    // MIDI state struct with 128 notes and 128 controls
    //
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct MidiVector3DeviceState : IInputStateTypeInfo
    {
        public FourCC format => new FourCC('M', 'I', 'D', 'V');

        #region Vec3 Notes(offset = 0x0000 to 0x127F)
        [InputControl(name = "Vec3Note000", displayName = "Vec3Note C -1", shortDisplayName = "V3N C -1", layout = "MidiNote", offset = 0x0000)]
        [InputControl(name = "Vec3Note001", displayName = "Vec3Note C#-1", shortDisplayName = "V3N C#-1", layout = "MidiNote", offset = 0x0010)]
        [InputControl(name = "Vec3Note002", displayName = "Vec3Note D -1", shortDisplayName = "V3N D -1", layout = "MidiNote", offset = 0x0020)]
        [InputControl(name = "Vec3Note003", displayName = "Vec3Note D#-1", shortDisplayName = "V3N D#-1", layout = "MidiNote", offset = 0x0030)]
        [InputControl(name = "Vec3Note004", displayName = "Vec3Note E -1", shortDisplayName = "V3N E -1", layout = "MidiNote", offset = 0x0040)]
        [InputControl(name = "Vec3Note005", displayName = "Vec3Note F -1", shortDisplayName = "V3N F -1", layout = "MidiNote", offset = 0x0050)]
        [InputControl(name = "Vec3Note006", displayName = "Vec3Note F#-1", shortDisplayName = "V3N F#-1", layout = "MidiNote", offset = 0x0060)]
        [InputControl(name = "Vec3Note007", displayName = "Vec3Note G -1", shortDisplayName = "V3N G -1", layout = "MidiNote", offset = 0x0070)]
        [InputControl(name = "Vec3Note008", displayName = "Vec3Note G#-1", shortDisplayName = "V3N G#-1", layout = "MidiNote", offset = 0x0080)]
        [InputControl(name = "Vec3Note009", displayName = "Vec3Note A -1", shortDisplayName = "V3N A -1", layout = "MidiNote", offset = 0x0090)]
        [InputControl(name = "Vec3Note010", displayName = "Vec3Note A#-1", shortDisplayName = "V3N A#-1", layout = "MidiNote", offset = 0x0100)]
        [InputControl(name = "Vec3Note011", displayName = "Vec3Note B -1", shortDisplayName = "V3N B -1", layout = "MidiNote", offset = 0x0110)]
        [InputControl(name = "Vec3Note012", displayName = "Vec3Note C  0", shortDisplayName = "V3N C  0", layout = "MidiNote", offset = 0x0120)]
        [InputControl(name = "Vec3Note013", displayName = "Vec3Note C# 0", shortDisplayName = "V3N C# 0", layout = "MidiNote", offset = 0x0130)]
        [InputControl(name = "Vec3Note014", displayName = "Vec3Note D  0", shortDisplayName = "V3N D  0", layout = "MidiNote", offset = 0x0140)]
        [InputControl(name = "Vec3Note015", displayName = "Vec3Note D# 0", shortDisplayName = "V3N D# 0", layout = "MidiNote", offset = 0x0150)]
        [InputControl(name = "Vec3Note016", displayName = "Vec3Note E  0", shortDisplayName = "V3N E  0", layout = "MidiNote", offset = 0x0160)]
        [InputControl(name = "Vec3Note017", displayName = "Vec3Note F  0", shortDisplayName = "V3N F  0", layout = "MidiNote", offset = 0x0170)]
        [InputControl(name = "Vec3Note018", displayName = "Vec3Note F# 0", shortDisplayName = "V3N F# 0", layout = "MidiNote", offset = 0x0180)]
        [InputControl(name = "Vec3Note019", displayName = "Vec3Note G  0", shortDisplayName = "V3N G  0", layout = "MidiNote", offset = 0x0190)]
        [InputControl(name = "Vec3Note020", displayName = "Vec3Note G# 0", shortDisplayName = "V3N G# 0", layout = "MidiNote", offset = 0x0200)]
        [InputControl(name = "Vec3Note021", displayName = "Vec3Note A  0", shortDisplayName = "V3N A  0", layout = "MidiNote", offset = 0x0210)]
        [InputControl(name = "Vec3Note022", displayName = "Vec3Note A# 0", shortDisplayName = "V3N A# 0", layout = "MidiNote", offset = 0x0220)]
        [InputControl(name = "Vec3Note023", displayName = "Vec3Note B  0", shortDisplayName = "V3N B  0", layout = "MidiNote", offset = 0x0230)]
        [InputControl(name = "Vec3Note024", displayName = "Vec3Note C  1", shortDisplayName = "V3N C  1", layout = "MidiNote", offset = 0x0240)]
        [InputControl(name = "Vec3Note025", displayName = "Vec3Note C# 1", shortDisplayName = "V3N C# 1", layout = "MidiNote", offset = 0x0250)]
        [InputControl(name = "Vec3Note026", displayName = "Vec3Note D  1", shortDisplayName = "V3N D  1", layout = "MidiNote", offset = 0x0260)]
        [InputControl(name = "Vec3Note027", displayName = "Vec3Note D# 1", shortDisplayName = "V3N D# 1", layout = "MidiNote", offset = 0x0270)]
        [InputControl(name = "Vec3Note028", displayName = "Vec3Note E  1", shortDisplayName = "V3N E  1", layout = "MidiNote", offset = 0x0280)]
        [InputControl(name = "Vec3Note029", displayName = "Vec3Note F  1", shortDisplayName = "V3N F  1", layout = "MidiNote", offset = 0x0290)]
        [InputControl(name = "Vec3Note030", displayName = "Vec3Note F# 1", shortDisplayName = "V3N F# 1", layout = "MidiNote", offset = 0x0300)]
        [InputControl(name = "Vec3Note031", displayName = "Vec3Note G  1", shortDisplayName = "V3N G  1", layout = "MidiNote", offset = 0x0310)]
        [InputControl(name = "Vec3Note032", displayName = "Vec3Note G# 1", shortDisplayName = "V3N G# 1", layout = "MidiNote", offset = 0x0320)]
        [InputControl(name = "Vec3Note033", displayName = "Vec3Note A  1", shortDisplayName = "V3N A  1", layout = "MidiNote", offset = 0x0330)]
        [InputControl(name = "Vec3Note034", displayName = "Vec3Note A# 1", shortDisplayName = "V3N A# 1", layout = "MidiNote", offset = 0x0340)]
        [InputControl(name = "Vec3Note035", displayName = "Vec3Note B  1", shortDisplayName = "V3N B  1", layout = "MidiNote", offset = 0x0350)]
        [InputControl(name = "Vec3Note036", displayName = "Vec3Note C  2", shortDisplayName = "V3N C  2", layout = "MidiNote", offset = 0x0360)]
        [InputControl(name = "Vec3Note037", displayName = "Vec3Note C# 2", shortDisplayName = "V3N C# 2", layout = "MidiNote", offset = 0x0370)]
        [InputControl(name = "Vec3Note038", displayName = "Vec3Note D  2", shortDisplayName = "V3N D  2", layout = "MidiNote", offset = 0x0380)]
        [InputControl(name = "Vec3Note039", displayName = "Vec3Note D# 2", shortDisplayName = "V3N D# 2", layout = "MidiNote", offset = 0x0390)]
        [InputControl(name = "Vec3Note040", displayName = "Vec3Note E  2", shortDisplayName = "V3N E  2", layout = "MidiNote", offset = 0x0400)]
        [InputControl(name = "Vec3Note041", displayName = "Vec3Note F  2", shortDisplayName = "V3N F  2", layout = "MidiNote", offset = 0x0410)]
        [InputControl(name = "Vec3Note042", displayName = "Vec3Note F# 2", shortDisplayName = "V3N F# 2", layout = "MidiNote", offset = 0x0420)]
        [InputControl(name = "Vec3Note043", displayName = "Vec3Note G  2", shortDisplayName = "V3N G  2", layout = "MidiNote", offset = 0x0430)]
        [InputControl(name = "Vec3Note044", displayName = "Vec3Note G# 2", shortDisplayName = "V3N G# 2", layout = "MidiNote", offset = 0x0440)]
        [InputControl(name = "Vec3Note045", displayName = "Vec3Note A  2", shortDisplayName = "V3N A  2", layout = "MidiNote", offset = 0x0450)]
        [InputControl(name = "Vec3Note046", displayName = "Vec3Note A# 2", shortDisplayName = "V3N A# 2", layout = "MidiNote", offset = 0x0460)]
        [InputControl(name = "Vec3Note047", displayName = "Vec3Note B  2", shortDisplayName = "V3N B  2", layout = "MidiNote", offset = 0x0470)]
        [InputControl(name = "Vec3Note048", displayName = "Vec3Note C  3", shortDisplayName = "V3N C  3", layout = "MidiNote", offset = 0x0480)]
        [InputControl(name = "Vec3Note049", displayName = "Vec3Note C# 3", shortDisplayName = "V3N C# 3", layout = "MidiNote", offset = 0x0490)]
        [InputControl(name = "Vec3Note050", displayName = "Vec3Note D  3", shortDisplayName = "V3N D  3", layout = "MidiNote", offset = 0x0500)]
        [InputControl(name = "Vec3Note051", displayName = "Vec3Note D# 3", shortDisplayName = "V3N D# 3", layout = "MidiNote", offset = 0x0510)]
        [InputControl(name = "Vec3Note052", displayName = "Vec3Note E  3", shortDisplayName = "V3N E  3", layout = "MidiNote", offset = 0x0520)]
        [InputControl(name = "Vec3Note053", displayName = "Vec3Note F  3", shortDisplayName = "V3N F  3", layout = "MidiNote", offset = 0x0530)]
        [InputControl(name = "Vec3Note054", displayName = "Vec3Note F# 3", shortDisplayName = "V3N F# 3", layout = "MidiNote", offset = 0x0540)]
        [InputControl(name = "Vec3Note055", displayName = "Vec3Note G  3", shortDisplayName = "V3N G  3", layout = "MidiNote", offset = 0x0550)]
        [InputControl(name = "Vec3Note056", displayName = "Vec3Note G# 3", shortDisplayName = "V3N G# 3", layout = "MidiNote", offset = 0x0560)]
        [InputControl(name = "Vec3Note057", displayName = "Vec3Note A  3", shortDisplayName = "V3N A  3", layout = "MidiNote", offset = 0x0570)]
        [InputControl(name = "Vec3Note058", displayName = "Vec3Note A# 3", shortDisplayName = "V3N A# 3", layout = "MidiNote", offset = 0x0580)]
        [InputControl(name = "Vec3Note059", displayName = "Vec3Note B  3", shortDisplayName = "V3N B  3", layout = "MidiNote", offset = 0x0590)]
        [InputControl(name = "Vec3Note060", displayName = "Vec3Note C  4", shortDisplayName = "V3N C  4", layout = "MidiNote", offset = 0x0600)]
        [InputControl(name = "Vec3Note061", displayName = "Vec3Note C# 4", shortDisplayName = "V3N C# 4", layout = "MidiNote", offset = 0x0610)]
        [InputControl(name = "Vec3Note062", displayName = "Vec3Note D  4", shortDisplayName = "V3N D  4", layout = "MidiNote", offset = 0x0620)]
        [InputControl(name = "Vec3Note063", displayName = "Vec3Note D# 4", shortDisplayName = "V3N D# 4", layout = "MidiNote", offset = 0x0630)]
        [InputControl(name = "Vec3Note064", displayName = "Vec3Note E  4", shortDisplayName = "V3N E  4", layout = "MidiNote", offset = 0x0640)]
        [InputControl(name = "Vec3Note065", displayName = "Vec3Note F  4", shortDisplayName = "V3N F  4", layout = "MidiNote", offset = 0x0650)]
        [InputControl(name = "Vec3Note066", displayName = "Vec3Note F# 4", shortDisplayName = "V3N F# 4", layout = "MidiNote", offset = 0x0660)]
        [InputControl(name = "Vec3Note067", displayName = "Vec3Note G  4", shortDisplayName = "V3N G  4", layout = "MidiNote", offset = 0x0670)]
        [InputControl(name = "Vec3Note068", displayName = "Vec3Note G# 4", shortDisplayName = "V3N G# 4", layout = "MidiNote", offset = 0x0680)]
        [InputControl(name = "Vec3Note069", displayName = "Vec3Note A  4", shortDisplayName = "V3N A  4", layout = "MidiNote", offset = 0x0690)]
        [InputControl(name = "Vec3Note070", displayName = "Vec3Note A# 4", shortDisplayName = "V3N A# 4", layout = "MidiNote", offset = 0x0700)]
        [InputControl(name = "Vec3Note071", displayName = "Vec3Note B  4", shortDisplayName = "V3N B  4", layout = "MidiNote", offset = 0x0710)]
        [InputControl(name = "Vec3Note072", displayName = "Vec3Note C  5", shortDisplayName = "V3N C  5", layout = "MidiNote", offset = 0x0720)]
        [InputControl(name = "Vec3Note073", displayName = "Vec3Note C# 5", shortDisplayName = "V3N C# 5", layout = "MidiNote", offset = 0x0730)]
        [InputControl(name = "Vec3Note074", displayName = "Vec3Note D  5", shortDisplayName = "V3N D  5", layout = "MidiNote", offset = 0x0740)]
        [InputControl(name = "Vec3Note075", displayName = "Vec3Note D# 5", shortDisplayName = "V3N D# 5", layout = "MidiNote", offset = 0x0750)]
        [InputControl(name = "Vec3Note076", displayName = "Vec3Note E  5", shortDisplayName = "V3N E  5", layout = "MidiNote", offset = 0x0760)]
        [InputControl(name = "Vec3Note077", displayName = "Vec3Note F  5", shortDisplayName = "V3N F  5", layout = "MidiNote", offset = 0x0770)]
        [InputControl(name = "Vec3Note078", displayName = "Vec3Note F# 5", shortDisplayName = "V3N F# 5", layout = "MidiNote", offset = 0x0780)]
        [InputControl(name = "Vec3Note079", displayName = "Vec3Note G  5", shortDisplayName = "V3N G  5", layout = "MidiNote", offset = 0x0790)]
        [InputControl(name = "Vec3Note080", displayName = "Vec3Note G# 5", shortDisplayName = "V3N G# 5", layout = "MidiNote", offset = 0x0800)]
        [InputControl(name = "Vec3Note081", displayName = "Vec3Note A  5", shortDisplayName = "V3N A  5", layout = "MidiNote", offset = 0x0810)]
        [InputControl(name = "Vec3Note082", displayName = "Vec3Note A# 5", shortDisplayName = "V3N A# 5", layout = "MidiNote", offset = 0x0820)]
        [InputControl(name = "Vec3Note083", displayName = "Vec3Note B  5", shortDisplayName = "V3N B  5", layout = "MidiNote", offset = 0x0830)]
        [InputControl(name = "Vec3Note084", displayName = "Vec3Note C  6", shortDisplayName = "V3N C  6", layout = "MidiNote", offset = 0x0840)]
        [InputControl(name = "Vec3Note085", displayName = "Vec3Note C# 6", shortDisplayName = "V3N C# 6", layout = "MidiNote", offset = 0x0850)]
        [InputControl(name = "Vec3Note086", displayName = "Vec3Note D  6", shortDisplayName = "V3N D  6", layout = "MidiNote", offset = 0x0860)]
        [InputControl(name = "Vec3Note087", displayName = "Vec3Note D# 6", shortDisplayName = "V3N D# 6", layout = "MidiNote", offset = 0x0870)]
        [InputControl(name = "Vec3Note088", displayName = "Vec3Note E  6", shortDisplayName = "V3N E  6", layout = "MidiNote", offset = 0x0880)]
        [InputControl(name = "Vec3Note089", displayName = "Vec3Note F  6", shortDisplayName = "V3N F  6", layout = "MidiNote", offset = 0x0890)]
        [InputControl(name = "Vec3Note090", displayName = "Vec3Note F# 6", shortDisplayName = "V3N F# 6", layout = "MidiNote", offset = 0x0900)]
        [InputControl(name = "Vec3Note091", displayName = "Vec3Note G  6", shortDisplayName = "V3N G  6", layout = "MidiNote", offset = 0x0910)]
        [InputControl(name = "Vec3Note092", displayName = "Vec3Note G# 6", shortDisplayName = "V3N G# 6", layout = "MidiNote", offset = 0x0920)]
        [InputControl(name = "Vec3Note093", displayName = "Vec3Note A  6", shortDisplayName = "V3N A  6", layout = "MidiNote", offset = 0x0930)]
        [InputControl(name = "Vec3Note094", displayName = "Vec3Note A# 6", shortDisplayName = "V3N A# 6", layout = "MidiNote", offset = 0x0940)]
        [InputControl(name = "Vec3Note095", displayName = "Vec3Note B  6", shortDisplayName = "V3N B  6", layout = "MidiNote", offset = 0x0950)]
        [InputControl(name = "Vec3Note096", displayName = "Vec3Note C  7", shortDisplayName = "V3N C  7", layout = "MidiNote", offset = 0x0960)]
        [InputControl(name = "Vec3Note097", displayName = "Vec3Note C# 7", shortDisplayName = "V3N C# 7", layout = "MidiNote", offset = 0x0970)]
        [InputControl(name = "Vec3Note098", displayName = "Vec3Note D  7", shortDisplayName = "V3N D  7", layout = "MidiNote", offset = 0x0980)]
        [InputControl(name = "Vec3Note099", displayName = "Vec3Note D# 7", shortDisplayName = "V3N D# 7", layout = "MidiNote", offset = 0x0990)]
        [InputControl(name = "Vec3Note100", displayName = "Vec3Note E  7", shortDisplayName = "V3N E  7", layout = "MidiNote", offset = 0x1000)]
        [InputControl(name = "Vec3Note101", displayName = "Vec3Note F  7", shortDisplayName = "V3N F  7", layout = "MidiNote", offset = 0x1010)]
        [InputControl(name = "Vec3Note102", displayName = "Vec3Note F# 7", shortDisplayName = "V3N F# 7", layout = "MidiNote", offset = 0x1020)]
        [InputControl(name = "Vec3Note103", displayName = "Vec3Note G  7", shortDisplayName = "V3N G  7", layout = "MidiNote", offset = 0x1030)]
        [InputControl(name = "Vec3Note104", displayName = "Vec3Note G# 7", shortDisplayName = "V3N G# 7", layout = "MidiNote", offset = 0x1040)]
        [InputControl(name = "Vec3Note105", displayName = "Vec3Note A  7", shortDisplayName = "V3N A  7", layout = "MidiNote", offset = 0x1050)]
        [InputControl(name = "Vec3Note106", displayName = "Vec3Note A# 7", shortDisplayName = "V3N A# 7", layout = "MidiNote", offset = 0x1060)]
        [InputControl(name = "Vec3Note107", displayName = "Vec3Note B  7", shortDisplayName = "V3N B  7", layout = "MidiNote", offset = 0x1070)]
        [InputControl(name = "Vec3Note108", displayName = "Vec3Note C  8", shortDisplayName = "V3N C  8", layout = "MidiNote", offset = 0x1080)]
        [InputControl(name = "Vec3Note109", displayName = "Vec3Note C# 8", shortDisplayName = "V3N C# 8", layout = "MidiNote", offset = 0x1090)]
        [InputControl(name = "Vec3Note110", displayName = "Vec3Note D  8", shortDisplayName = "V3N D  8", layout = "MidiNote", offset = 0x1100)]
        [InputControl(name = "Vec3Note111", displayName = "Vec3Note D# 8", shortDisplayName = "V3N D# 8", layout = "MidiNote", offset = 0x1110)]
        [InputControl(name = "Vec3Note112", displayName = "Vec3Note E  8", shortDisplayName = "V3N E  8", layout = "MidiNote", offset = 0x1120)]
        [InputControl(name = "Vec3Note113", displayName = "Vec3Note F  8", shortDisplayName = "V3N F  8", layout = "MidiNote", offset = 0x1130)]
        [InputControl(name = "Vec3Note114", displayName = "Vec3Note F# 8", shortDisplayName = "V3N F# 8", layout = "MidiNote", offset = 0x1140)]
        [InputControl(name = "Vec3Note115", displayName = "Vec3Note G  8", shortDisplayName = "V3N G  8", layout = "MidiNote", offset = 0x1150)]
        [InputControl(name = "Vec3Note116", displayName = "Vec3Note G# 8", shortDisplayName = "V3N G# 8", layout = "MidiNote", offset = 0x1160)]
        [InputControl(name = "Vec3Note117", displayName = "Vec3Note A  8", shortDisplayName = "V3N A  8", layout = "MidiNote", offset = 0x1170)]
        [InputControl(name = "Vec3Note118", displayName = "Vec3Note A# 8", shortDisplayName = "V3N A# 8", layout = "MidiNote", offset = 0x1180)]
        [InputControl(name = "Vec3Note119", displayName = "Vec3Note B  8", shortDisplayName = "V3N B  8", layout = "MidiNote", offset = 0x1190)]
        [InputControl(name = "Vec3Note120", displayName = "Vec3Note C  9", shortDisplayName = "V3N C  9", layout = "MidiNote", offset = 0x1200)]
        [InputControl(name = "Vec3Note121", displayName = "Vec3Note C# 9", shortDisplayName = "V3N C# 9", layout = "MidiNote", offset = 0x1210)]
        [InputControl(name = "Vec3Note122", displayName = "Vec3Note D  9", shortDisplayName = "V3N D  9", layout = "MidiNote", offset = 0x1220)]
        [InputControl(name = "Vec3Note123", displayName = "Vec3Note D# 9", shortDisplayName = "V3N D# 9", layout = "MidiNote", offset = 0x1230)]
        [InputControl(name = "Vec3Note124", displayName = "Vec3Note E  9", shortDisplayName = "V3N E  9", layout = "MidiNote", offset = 0x1240)]
        [InputControl(name = "Vec3Note125", displayName = "Vec3Note F  9", shortDisplayName = "V3N F  9", layout = "MidiNote", offset = 0x1250)]
        [InputControl(name = "Vec3Note126", displayName = "Vec3Note F# 9", shortDisplayName = "V3N F# 9", layout = "MidiNote", offset = 0x1260)]
        [InputControl(name = "Vec3Note127", displayName = "Vec3Note G  9", shortDisplayName = "V3N G  9", layout = "MidiNote", offset = 0x1270)]
        public fixed byte vec3notes[128];
        #endregion

        #region Default ControlChanges(offset = 0x1280 to 0x255F)
        [InputControl(name = "Vec3Control000", displayName = "Vec3Control 0"  , shortDisplayName = "V3CC 0"  , layout = "MidiValue", offset = 0x1280)]
        [InputControl(name = "Vec3Control001", displayName = "Vec3Control 1"  , shortDisplayName = "V3CC 1"  , layout = "MidiValue", offset = 0x1290)]
        [InputControl(name = "Vec3Control002", displayName = "Vec3Control 2"  , shortDisplayName = "V3CC 2"  , layout = "MidiValue", offset = 0x1300)]
        [InputControl(name = "Vec3Control003", displayName = "Vec3Control 3"  , shortDisplayName = "V3CC 3"  , layout = "MidiValue", offset = 0x1310)]
        [InputControl(name = "Vec3Control004", displayName = "Vec3Control 4"  , shortDisplayName = "V3CC 4"  , layout = "MidiValue", offset = 0x1320)]
        [InputControl(name = "Vec3Control005", displayName = "Vec3Control 5"  , shortDisplayName = "V3CC 5"  , layout = "MidiValue", offset = 0x1330)]
        [InputControl(name = "Vec3Control006", displayName = "Vec3Control 6"  , shortDisplayName = "V3CC 6"  , layout = "MidiValue", offset = 0x1340)]
        [InputControl(name = "Vec3Control007", displayName = "Vec3Control 7"  , shortDisplayName = "V3CC 7"  , layout = "MidiValue", offset = 0x1350)]
        [InputControl(name = "Vec3Control008", displayName = "Vec3Control 8"  , shortDisplayName = "V3CC 8"  , layout = "MidiValue", offset = 0x1360)]
        [InputControl(name = "Vec3Control009", displayName = "Vec3Control 9"  , shortDisplayName = "V3CC 9"  , layout = "MidiValue", offset = 0x1370)]
        [InputControl(name = "Vec3Control010", displayName = "Vec3Control 10" , shortDisplayName = "V3CC 10" , layout = "MidiValue", offset = 0x1380)]
        [InputControl(name = "Vec3Control011", displayName = "Vec3Control 11" , shortDisplayName = "V3CC 11" , layout = "MidiValue", offset = 0x1390)]
        [InputControl(name = "Vec3Control012", displayName = "Vec3Control 12" , shortDisplayName = "V3CC 12" , layout = "MidiValue", offset = 0x1400)]
        [InputControl(name = "Vec3Control013", displayName = "Vec3Control 13" , shortDisplayName = "V3CC 13" , layout = "MidiValue", offset = 0x1410)]
        [InputControl(name = "Vec3Control014", displayName = "Vec3Control 14" , shortDisplayName = "V3CC 14" , layout = "MidiValue", offset = 0x1420)]
        [InputControl(name = "Vec3Control015", displayName = "Vec3Control 15" , shortDisplayName = "V3CC 15" , layout = "MidiValue", offset = 0x1430)]
        [InputControl(name = "Vec3Control016", displayName = "Vec3Control 16" , shortDisplayName = "V3CC 16" , layout = "MidiValue", offset = 0x1440)]
        [InputControl(name = "Vec3Control017", displayName = "Vec3Control 17" , shortDisplayName = "V3CC 17" , layout = "MidiValue", offset = 0x1450)]
        [InputControl(name = "Vec3Control018", displayName = "Vec3Control 18" , shortDisplayName = "V3CC 18" , layout = "MidiValue", offset = 0x1460)]
        [InputControl(name = "Vec3Control019", displayName = "Vec3Control 19" , shortDisplayName = "V3CC 19" , layout = "MidiValue", offset = 0x1470)]
        [InputControl(name = "Vec3Control020", displayName = "Vec3Control 20" , shortDisplayName = "V3CC 20" , layout = "MidiValue", offset = 0x1480)]
        [InputControl(name = "Vec3Control021", displayName = "Vec3Control 21" , shortDisplayName = "V3CC 21" , layout = "MidiValue", offset = 0x1490)]
        [InputControl(name = "Vec3Control022", displayName = "Vec3Control 22" , shortDisplayName = "V3CC 22" , layout = "MidiValue", offset = 0x1500)]
        [InputControl(name = "Vec3Control023", displayName = "Vec3Control 23" , shortDisplayName = "V3CC 23" , layout = "MidiValue", offset = 0x1510)]
        [InputControl(name = "Vec3Control024", displayName = "Vec3Control 24" , shortDisplayName = "V3CC 24" , layout = "MidiValue", offset = 0x1520)]
        [InputControl(name = "Vec3Control025", displayName = "Vec3Control 25" , shortDisplayName = "V3CC 25" , layout = "MidiValue", offset = 0x1530)]
        [InputControl(name = "Vec3Control026", displayName = "Vec3Control 26" , shortDisplayName = "V3CC 26" , layout = "MidiValue", offset = 0x1540)]
        [InputControl(name = "Vec3Control027", displayName = "Vec3Control 27" , shortDisplayName = "V3CC 27" , layout = "MidiValue", offset = 0x1550)]
        [InputControl(name = "Vec3Control028", displayName = "Vec3Control 28" , shortDisplayName = "V3CC 28" , layout = "MidiValue", offset = 0x1560)]
        [InputControl(name = "Vec3Control029", displayName = "Vec3Control 29" , shortDisplayName = "V3CC 29" , layout = "MidiValue", offset = 0x1570)]
        [InputControl(name = "Vec3Control030", displayName = "Vec3Control 30" , shortDisplayName = "V3CC 30" , layout = "MidiValue", offset = 0x1580)]
        [InputControl(name = "Vec3Control031", displayName = "Vec3Control 31" , shortDisplayName = "V3CC 31" , layout = "MidiValue", offset = 0x1590)]
        [InputControl(name = "Vec3Control032", displayName = "Vec3Control 32" , shortDisplayName = "V3CC 32" , layout = "MidiValue", offset = 0x1600)]
        [InputControl(name = "Vec3Control033", displayName = "Vec3Control 33" , shortDisplayName = "V3CC 33" , layout = "MidiValue", offset = 0x1610)]
        [InputControl(name = "Vec3Control034", displayName = "Vec3Control 34" , shortDisplayName = "V3CC 34" , layout = "MidiValue", offset = 0x1620)]
        [InputControl(name = "Vec3Control035", displayName = "Vec3Control 35" , shortDisplayName = "V3CC 35" , layout = "MidiValue", offset = 0x1630)]
        [InputControl(name = "Vec3Control036", displayName = "Vec3Control 36" , shortDisplayName = "V3CC 36" , layout = "MidiValue", offset = 0x1640)]
        [InputControl(name = "Vec3Control037", displayName = "Vec3Control 37" , shortDisplayName = "V3CC 37" , layout = "MidiValue", offset = 0x1650)]
        [InputControl(name = "Vec3Control038", displayName = "Vec3Control 38" , shortDisplayName = "V3CC 38" , layout = "MidiValue", offset = 0x1660)]
        [InputControl(name = "Vec3Control039", displayName = "Vec3Control 39" , shortDisplayName = "V3CC 39" , layout = "MidiValue", offset = 0x1670)]
        [InputControl(name = "Vec3Control040", displayName = "Vec3Control 40" , shortDisplayName = "V3CC 40" , layout = "MidiValue", offset = 0x1680)]
        [InputControl(name = "Vec3Control041", displayName = "Vec3Control 41" , shortDisplayName = "V3CC 41" , layout = "MidiValue", offset = 0x1690)]
        [InputControl(name = "Vec3Control042", displayName = "Vec3Control 42" , shortDisplayName = "V3CC 42" , layout = "MidiValue", offset = 0x1700)]
        [InputControl(name = "Vec3Control043", displayName = "Vec3Control 43" , shortDisplayName = "V3CC 43" , layout = "MidiValue", offset = 0x1710)]
        [InputControl(name = "Vec3Control044", displayName = "Vec3Control 44" , shortDisplayName = "V3CC 44" , layout = "MidiValue", offset = 0x1720)]
        [InputControl(name = "Vec3Control045", displayName = "Vec3Control 45" , shortDisplayName = "V3CC 45" , layout = "MidiValue", offset = 0x1730)]
        [InputControl(name = "Vec3Control046", displayName = "Vec3Control 46" , shortDisplayName = "V3CC 46" , layout = "MidiValue", offset = 0x1740)]
        [InputControl(name = "Vec3Control047", displayName = "Vec3Control 47" , shortDisplayName = "V3CC 47" , layout = "MidiValue", offset = 0x1750)]
        [InputControl(name = "Vec3Control048", displayName = "Vec3Control 48" , shortDisplayName = "V3CC 48" , layout = "MidiValue", offset = 0x1760)]
        [InputControl(name = "Vec3Control049", displayName = "Vec3Control 49" , shortDisplayName = "V3CC 49" , layout = "MidiValue", offset = 0x1770)]
        [InputControl(name = "Vec3Control050", displayName = "Vec3Control 50" , shortDisplayName = "V3CC 50" , layout = "MidiValue", offset = 0x1780)]
        [InputControl(name = "Vec3Control051", displayName = "Vec3Control 51" , shortDisplayName = "V3CC 51" , layout = "MidiValue", offset = 0x1790)]
        [InputControl(name = "Vec3Control052", displayName = "Vec3Control 52" , shortDisplayName = "V3CC 52" , layout = "MidiValue", offset = 0x1800)]
        [InputControl(name = "Vec3Control053", displayName = "Vec3Control 53" , shortDisplayName = "V3CC 53" , layout = "MidiValue", offset = 0x1810)]
        [InputControl(name = "Vec3Control054", displayName = "Vec3Control 54" , shortDisplayName = "V3CC 54" , layout = "MidiValue", offset = 0x1820)]
        [InputControl(name = "Vec3Control055", displayName = "Vec3Control 55" , shortDisplayName = "V3CC 55" , layout = "MidiValue", offset = 0x1830)]
        [InputControl(name = "Vec3Control056", displayName = "Vec3Control 56" , shortDisplayName = "V3CC 56" , layout = "MidiValue", offset = 0x1840)]
        [InputControl(name = "Vec3Control057", displayName = "Vec3Control 57" , shortDisplayName = "V3CC 57" , layout = "MidiValue", offset = 0x1850)]
        [InputControl(name = "Vec3Control058", displayName = "Vec3Control 58" , shortDisplayName = "V3CC 58" , layout = "MidiValue", offset = 0x1860)]
        [InputControl(name = "Vec3Control059", displayName = "Vec3Control 59" , shortDisplayName = "V3CC 59" , layout = "MidiValue", offset = 0x1870)]
        [InputControl(name = "Vec3Control060", displayName = "Vec3Control 60" , shortDisplayName = "V3CC 60" , layout = "MidiValue", offset = 0x1880)]
        [InputControl(name = "Vec3Control061", displayName = "Vec3Control 61" , shortDisplayName = "V3CC 61" , layout = "MidiValue", offset = 0x1890)]
        [InputControl(name = "Vec3Control062", displayName = "Vec3Control 62" , shortDisplayName = "V3CC 62" , layout = "MidiValue", offset = 0x1900)]
        [InputControl(name = "Vec3Control063", displayName = "Vec3Control 63" , shortDisplayName = "V3CC 63" , layout = "MidiValue", offset = 0x1910)]
        [InputControl(name = "Vec3Control064", displayName = "Vec3Control 64" , shortDisplayName = "V3CC 64" , layout = "MidiValue", offset = 0x1920)]
        [InputControl(name = "Vec3Control065", displayName = "Vec3Control 65" , shortDisplayName = "V3CC 65" , layout = "MidiValue", offset = 0x1930)]
        [InputControl(name = "Vec3Control066", displayName = "Vec3Control 66" , shortDisplayName = "V3CC 66" , layout = "MidiValue", offset = 0x1940)]
        [InputControl(name = "Vec3Control067", displayName = "Vec3Control 67" , shortDisplayName = "V3CC 67" , layout = "MidiValue", offset = 0x1950)]
        [InputControl(name = "Vec3Control068", displayName = "Vec3Control 68" , shortDisplayName = "V3CC 68" , layout = "MidiValue", offset = 0x1960)]
        [InputControl(name = "Vec3Control069", displayName = "Vec3Control 69" , shortDisplayName = "V3CC 69" , layout = "MidiValue", offset = 0x1970)]
        [InputControl(name = "Vec3Control070", displayName = "Vec3Control 70" , shortDisplayName = "V3CC 70" , layout = "MidiValue", offset = 0x1980)]
        [InputControl(name = "Vec3Control071", displayName = "Vec3Control 71" , shortDisplayName = "V3CC 71" , layout = "MidiValue", offset = 0x1990)]
        [InputControl(name = "Vec3Control072", displayName = "Vec3Control 72" , shortDisplayName = "V3CC 72" , layout = "MidiValue", offset = 0x2000)]
        [InputControl(name = "Vec3Control073", displayName = "Vec3Control 73" , shortDisplayName = "V3CC 73" , layout = "MidiValue", offset = 0x2010)]
        [InputControl(name = "Vec3Control074", displayName = "Vec3Control 74" , shortDisplayName = "V3CC 74" , layout = "MidiValue", offset = 0x2020)]
        [InputControl(name = "Vec3Control075", displayName = "Vec3Control 75" , shortDisplayName = "V3CC 75" , layout = "MidiValue", offset = 0x2030)]
        [InputControl(name = "Vec3Control076", displayName = "Vec3Control 76" , shortDisplayName = "V3CC 76" , layout = "MidiValue", offset = 0x2040)]
        [InputControl(name = "Vec3Control077", displayName = "Vec3Control 77" , shortDisplayName = "V3CC 77" , layout = "MidiValue", offset = 0x2050)]
        [InputControl(name = "Vec3Control078", displayName = "Vec3Control 78" , shortDisplayName = "V3CC 78" , layout = "MidiValue", offset = 0x2060)]
        [InputControl(name = "Vec3Control079", displayName = "Vec3Control 79" , shortDisplayName = "V3CC 79" , layout = "MidiValue", offset = 0x2070)]
        [InputControl(name = "Vec3Control080", displayName = "Vec3Control 80" , shortDisplayName = "V3CC 80" , layout = "MidiValue", offset = 0x2080)]
        [InputControl(name = "Vec3Control081", displayName = "Vec3Control 81" , shortDisplayName = "V3CC 81" , layout = "MidiValue", offset = 0x2090)]
        [InputControl(name = "Vec3Control082", displayName = "Vec3Control 82" , shortDisplayName = "V3CC 82" , layout = "MidiValue", offset = 0x2100)]
        [InputControl(name = "Vec3Control083", displayName = "Vec3Control 83" , shortDisplayName = "V3CC 83" , layout = "MidiValue", offset = 0x2110)]
        [InputControl(name = "Vec3Control084", displayName = "Vec3Control 84" , shortDisplayName = "V3CC 84" , layout = "MidiValue", offset = 0x2120)]
        [InputControl(name = "Vec3Control085", displayName = "Vec3Control 85" , shortDisplayName = "V3CC 85" , layout = "MidiValue", offset = 0x2130)]
        [InputControl(name = "Vec3Control086", displayName = "Vec3Control 86" , shortDisplayName = "V3CC 86" , layout = "MidiValue", offset = 0x2140)]
        [InputControl(name = "Vec3Control087", displayName = "Vec3Control 87" , shortDisplayName = "V3CC 87" , layout = "MidiValue", offset = 0x2150)]
        [InputControl(name = "Vec3Control088", displayName = "Vec3Control 88" , shortDisplayName = "V3CC 88" , layout = "MidiValue", offset = 0x2160)]
        [InputControl(name = "Vec3Control089", displayName = "Vec3Control 89" , shortDisplayName = "V3CC 89" , layout = "MidiValue", offset = 0x2170)]
        [InputControl(name = "Vec3Control090", displayName = "Vec3Control 90" , shortDisplayName = "V3CC 90" , layout = "MidiValue", offset = 0x2180)]
        [InputControl(name = "Vec3Control091", displayName = "Vec3Control 91" , shortDisplayName = "V3CC 91" , layout = "MidiValue", offset = 0x2190)]
        [InputControl(name = "Vec3Control092", displayName = "Vec3Control 92" , shortDisplayName = "V3CC 92" , layout = "MidiValue", offset = 0x2200)]
        [InputControl(name = "Vec3Control093", displayName = "Vec3Control 93" , shortDisplayName = "V3CC 93" , layout = "MidiValue", offset = 0x2210)]
        [InputControl(name = "Vec3Control094", displayName = "Vec3Control 94" , shortDisplayName = "V3CC 94" , layout = "MidiValue", offset = 0x2220)]
        [InputControl(name = "Vec3Control095", displayName = "Vec3Control 95" , shortDisplayName = "V3CC 95" , layout = "MidiValue", offset = 0x2230)]
        [InputControl(name = "Vec3Control096", displayName = "Vec3Control 96" , shortDisplayName = "V3CC 96" , layout = "MidiValue", offset = 0x2240)]
        [InputControl(name = "Vec3Control097", displayName = "Vec3Control 97" , shortDisplayName = "V3CC 97" , layout = "MidiValue", offset = 0x2250)]
        [InputControl(name = "Vec3Control098", displayName = "Vec3Control 98" , shortDisplayName = "V3CC 98" , layout = "MidiValue", offset = 0x2260)]
        [InputControl(name = "Vec3Control099", displayName = "Vec3Control 99" , shortDisplayName = "V3CC 99" , layout = "MidiValue", offset = 0x2270)]
        [InputControl(name = "Vec3Control100", displayName = "Vec3Control 100", shortDisplayName = "V3CC 100", layout = "MidiValue", offset = 0x2280)]
        [InputControl(name = "Vec3Control101", displayName = "Vec3Control 101", shortDisplayName = "V3CC 101", layout = "MidiValue", offset = 0x2290)]
        [InputControl(name = "Vec3Control102", displayName = "Vec3Control 102", shortDisplayName = "V3CC 102", layout = "MidiValue", offset = 0x2300)]
        [InputControl(name = "Vec3Control103", displayName = "Vec3Control 103", shortDisplayName = "V3CC 103", layout = "MidiValue", offset = 0x2310)]
        [InputControl(name = "Vec3Control104", displayName = "Vec3Control 104", shortDisplayName = "V3CC 104", layout = "MidiValue", offset = 0x2320)]
        [InputControl(name = "Vec3Control105", displayName = "Vec3Control 105", shortDisplayName = "V3CC 105", layout = "MidiValue", offset = 0x2330)]
        [InputControl(name = "Vec3Control106", displayName = "Vec3Control 106", shortDisplayName = "V3CC 106", layout = "MidiValue", offset = 0x2340)]
        [InputControl(name = "Vec3Control107", displayName = "Vec3Control 107", shortDisplayName = "V3CC 107", layout = "MidiValue", offset = 0x2350)]
        [InputControl(name = "Vec3Control108", displayName = "Vec3Control 108", shortDisplayName = "V3CC 108", layout = "MidiValue", offset = 0x2360)]
        [InputControl(name = "Vec3Control109", displayName = "Vec3Control 109", shortDisplayName = "V3CC 109", layout = "MidiValue", offset = 0x2370)]
        [InputControl(name = "Vec3Control110", displayName = "Vec3Control 110", shortDisplayName = "V3CC 110", layout = "MidiValue", offset = 0x2380)]
        [InputControl(name = "Vec3Control111", displayName = "Vec3Control 111", shortDisplayName = "V3CC 111", layout = "MidiValue", offset = 0x2390)]
        [InputControl(name = "Vec3Control112", displayName = "Vec3Control 112", shortDisplayName = "V3CC 112", layout = "MidiValue", offset = 0x2400)]
        [InputControl(name = "Vec3Control113", displayName = "Vec3Control 113", shortDisplayName = "V3CC 113", layout = "MidiValue", offset = 0x2410)]
        [InputControl(name = "Vec3Control114", displayName = "Vec3Control 114", shortDisplayName = "V3CC 114", layout = "MidiValue", offset = 0x2420)]
        [InputControl(name = "Vec3Control115", displayName = "Vec3Control 115", shortDisplayName = "V3CC 115", layout = "MidiValue", offset = 0x2430)]
        [InputControl(name = "Vec3Control116", displayName = "Vec3Control 116", shortDisplayName = "V3CC 116", layout = "MidiValue", offset = 0x2440)]
        [InputControl(name = "Vec3Control117", displayName = "Vec3Control 117", shortDisplayName = "V3CC 117", layout = "MidiValue", offset = 0x2450)]
        [InputControl(name = "Vec3Control118", displayName = "Vec3Control 118", shortDisplayName = "V3CC 118", layout = "MidiValue", offset = 0x2460)]
        [InputControl(name = "Vec3Control119", displayName = "Vec3Control 119", shortDisplayName = "V3CC 119", layout = "MidiValue", offset = 0x2470)]
        [InputControl(name = "Vec3Control120", displayName = "Vec3Control 120", shortDisplayName = "V3CC 120", layout = "MidiValue", offset = 0x2480)]
        [InputControl(name = "Vec3Control121", displayName = "Vec3Control 121", shortDisplayName = "V3CC 121", layout = "MidiValue", offset = 0x2490)]
        [InputControl(name = "Vec3Control122", displayName = "Vec3Control 122", shortDisplayName = "V3CC 122", layout = "MidiValue", offset = 0x2500)]
        [InputControl(name = "Vec3Control123", displayName = "Vec3Control 123", shortDisplayName = "V3CC 123", layout = "MidiValue", offset = 0x2510)]
        [InputControl(name = "Vec3Control124", displayName = "Vec3Control 124", shortDisplayName = "V3CC 124", layout = "MidiValue", offset = 0x2520)]
        [InputControl(name = "Vec3Control125", displayName = "Vec3Control 125", shortDisplayName = "V3CC 125", layout = "MidiValue", offset = 0x2530)]
        [InputControl(name = "Vec3Control126", displayName = "Vec3Control 126", shortDisplayName = "V3CC 126", layout = "MidiValue", offset = 0x2540)]
        [InputControl(name = "Vec3Control127", displayName = "Vec3Control 127", shortDisplayName = "V3CC 127", layout = "MidiValue", offset = 0x2550)]
        public fixed byte controls[128];
        #endregion

        #region Others(offset = 0x2560 to 0x385F)
        [InputControl(name = "PitchBend", displayName = "PitchBend", shortDisplayName = "Pitch", layout = "MidiPitch", offset = 0x2560)]
        public fixed byte pitchBned[1];
        [InputControl(name = "PitchUp", displayName = "PitchBendUp", shortDisplayName = "PitchUp", layout = "MidiPitchUp", offset = 0x2570)]
        public fixed byte pitchUp[1];
        [InputControl(name = "PitchDown", displayName = "PitchBendDown", shortDisplayName = "PitchDown", layout = "MidiPitchDown", offset = 0x2580)]
        public fixed byte pitchDown[1];
        [InputControl(name = "ProgramChange", displayName = "ProgramChange", shortDisplayName = "PC", layout = "MidiProgramChange", offset = 0x2590)]
        public fixed byte programChange[1];
        [InputControl(name = "AnyNote",         displayName = "AnyNote",        shortDisplayName = "AnyNote",   layout = "MidiNote", offset = 0x2600)]
        [InputControl(name = "AnyWhiteNote",    displayName = "AnyWhiteNote",   shortDisplayName = "AnyWNote",  layout = "MidiNote", offset = 0x2610)]
        [InputControl(name = "AnyBlackNote",    displayName = "AnyBlackNote",   shortDisplayName = "AnyBNote",  layout = "MidiNote", offset = 0x2620)]
        public fixed byte anyNote[3];
        #endregion

    }
}
